// GENERATED by the lens-library import (K-261, curated to twenty K-264) -
// regenerate rather than edit. Prescriptions are transcribed patent data
// (photonstophotos.net Optical Bench, via the FlareSim collection); each
// file cites its patent. Factual optical tables, embedded as text and
// parsed on selection.
//
// Twenty, down from 1299 (K-264, owner-decided): a thousand-entry picker
// is a search problem, not a choice; these twenty are curated for
// maximally DIFFERENT flare characters - modern multicoated cine glass, a
// 1930s uncoated double Gauss, a four-element Tessar, an f0.95, fisheyes
// and process lenses, superzooms and long telephotos - and a user .lens
// file (the `lens_file` parameter) covers everything else.

/// One bundled lens prescription: display name, native f-number parsed
/// from the collection filename (0.0 = unknown, estimate from geometry),
/// and the .lens text.
pub struct LensFile {
    pub name: &'static str,
    pub native_fstop: f32,
    pub text: &'static str,
}

pub static LENS_LIBRARY: [LensFile; 20] = [
    LensFile { name: "7Artisans · 50mm F0.95", native_fstop: 0.95, text: include_str!("../../lens_files/7Artisans_50mm_F0.95_(7Artisans_APS-C_50mm_F0.95).lens") },
    LensFile { name: "Angenieux · 35mm f2.5 R1", native_fstop: 0.00, text: include_str!("../../lens_files/Angenieux_35mm_f2.5_(Angenieux_35mm_f2.5_R1).lens") },
    LensFile { name: "Canon · 8.8-36.8mm f1.8-2.8 (PowerShot G7X)", native_fstop: 1.85, text: include_str!("../../lens_files/Canon_9-36mm_F1.85-2.88_(Canon_8.8-36.8mm_f1.8-2.8[PowerShot_G7X]).lens") },
    LensFile { name: "Canon · 85mm f1.5 (1952)", native_fstop: 1.50, text: include_str!("../../lens_files/Canon_85mm_F1.5_(Canon_85mm_f1.5).lens") },
    LensFile { name: "Canon · EF 100mm f2.8 Macro", native_fstop: 2.89, text: include_str!("../../lens_files/Canon_100mm_F2.89_macro_(Canon_EF100mm_f2.8_Macro).lens") },
    LensFile { name: "Canon · EF 400mm f2.8L IS II", native_fstop: 2.90, text: include_str!("../../lens_files/Canon_392mm_F2.9_(Canon_EF400mm_f2.8L_IS_II_USM).lens") },
    LensFile { name: "Canon · EF 70-200mm f2.8L", native_fstop: 2.92, text: include_str!("../../lens_files/Canon_72-194mm_F2.923_IZ_(Canon_EF70-200mm_f2.8L_USM).lens") },
    LensFile { name: "Canon · EF-S 18-200mm f3.5-5.6 IS", native_fstop: 3.60, text: include_str!("../../lens_files/Canon_19-193mm_F3.6-5.88_OS_(Canon_EF-S18-200mm_f3.5-5.6_IS).lens") },
    LensFile { name: "GOI · Russar-22", native_fstop: 8.00, text: include_str!("../../lens_files/69.88mm_F8_(GOI_Russar-22).lens") },
    LensFile { name: "Kinoptik · Tegea 5.7mm f1.8", native_fstop: 1.80, text: include_str!("../../lens_files/Kinoptik_5.8mm_F1.8_(Kinoptik_Tegea_5.7mm_F1.8).lens") },
    LensFile { name: "Leica · Summilux 35mm f1.4", native_fstop: 1.40, text: include_str!("../../lens_files/Leica_35mm_F1.4_(Leica_Summilux_35mm_F1.4).lens") },
    LensFile { name: "Meyer Görlitz · Kino Plasmat 100mm F2", native_fstop: 2.00, text: include_str!("../../lens_files/Meyer_100mm_F2_(Meyer_Optik_Gorlitz_100mm_F2_Kino_Plasmat).lens") },
    LensFile { name: "Meyer Görlitz · Orestegor 500mm F5.6", native_fstop: 5.60, text: include_str!("../../lens_files/Meyer_500mm_F5.6_(Meyer_Optik_Goerlitz_500mm_F5.6_Orestegor).lens") },
    LensFile { name: "Nikon · Fisheye-Nikkor 6mm f2.8", native_fstop: 2.80, text: include_str!("../../lens_files/Nikon_6mm_F2.8_220_degree_fisheye_Y23.22mm_(Nikon_Fisheye-Nikkor_6mm_F2.8).lens") },
    LensFile { name: "Projection Optics · Super-Lite 100mm F2.2", native_fstop: 2.20, text: include_str!("../../lens_files/Projection_Optics_100mm_F2.2_(Projection_Optics_Super-Lite).lens") },
    LensFile { name: "Ross · F10 APO Process Xpres", native_fstop: 10.00, text: include_str!("../../lens_files/100mm_F10_(Ross_F10_APO_Process_Xpres).lens") },
    LensFile { name: "Sigma · 14mm F1.8 Art", native_fstop: 1.85, text: include_str!("../../lens_files/Sigma_14mm_F1.85_IF.lens") },
    LensFile { name: "Zeiss · Arri Master Prime T1.3 50mm", native_fstop: 1.30, text: include_str!("../../lens_files/Zeiss_50mm_F1.3_(Arri_Zeiss_Master_Prime_T1.3_50mm).lens") },
    LensFile { name: "Zeiss · Biotar 50mm F1.4", native_fstop: 1.40, text: include_str!("../../lens_files/Zeiss_50mm_F1.4_(Zeiss_Biotar_50mm_F1.4).lens") },
    LensFile { name: "Zeiss · Tessar 50mm F2.8", native_fstop: 2.80, text: include_str!("../../lens_files/Zeiss_50mm_F2.8_(Zeiss_Tessar_f2.8_50mm).lens") },
];

/// The Lens dropdown's labels, index-aligned with [`LENS_LIBRARY`].
pub static LENS_OPTIONS: [&str; 20] = [
    "7Artisans · 50mm F0.95",
    "Angenieux · 35mm f2.5 R1",
    "Canon · 8.8-36.8mm f1.8-2.8 (PowerShot G7X)",
    "Canon · 85mm f1.5 (1952)",
    "Canon · EF 100mm f2.8 Macro",
    "Canon · EF 400mm f2.8L IS II",
    "Canon · EF 70-200mm f2.8L",
    "Canon · EF-S 18-200mm f3.5-5.6 IS",
    "GOI · Russar-22",
    "Kinoptik · Tegea 5.7mm f1.8",
    "Leica · Summilux 35mm f1.4",
    "Meyer Görlitz · Kino Plasmat 100mm F2",
    "Meyer Görlitz · Orestegor 500mm F5.6",
    "Nikon · Fisheye-Nikkor 6mm f2.8",
    "Projection Optics · Super-Lite 100mm F2.2",
    "Ross · F10 APO Process Xpres",
    "Sigma · 14mm F1.8 Art",
    "Zeiss · Arri Master Prime T1.3 50mm",
    "Zeiss · Biotar 50mm F1.4",
    "Zeiss · Tessar 50mm F2.8",
];
