//! lumit-bridge: the seam the Flutter frontend calls the Rust engine through
//! (docs/archive/flutter-port/03-ARCHITECTURE.md).
//!
//! # In plain terms
//!
//! The Flutter application is written in Dart and cannot call Rust functions
//! directly. This crate is the translator between them. It compiles to a single
//! shared library (a `.dll` on Windows) that Dart loads at start-up; Dart then
//! calls the plain C functions this crate exports — `lumit_bridge_new_project`,
//! `lumit_bridge_snapshot`, and so on — passing text in and getting text back.
//!
//! The text is JSON (docs call this "bridge v0", a hand-rolled JSON-over-C-ABI
//! seam we keep until the API stabilises and `flutter_rust_bridge` generates
//! this layer instead). Every call returns a UTF-8, NUL-terminated string that
//! Rust allocated; the caller reads it and then hands it back to
//! [`ffi::lumit_bridge_free_string`] so Rust can release the memory. Every reply
//! is either `{"ok":true, …}` or `{"ok":false,"error":"…"}` — the error is a
//! calm sentence for the status line, never a crash.
//!
//! The one exception to "everything is JSON" is [`ffi::lumit_bridge_decode_frame`],
//! which returns a raw block of RGBA pixels (a video frame is far too large to
//! encode as text); it has its own ownership contract, documented beside
//! [`ffi::lumit_bridge_free_buffer`].
//!
//! The engine-side document and its undo history live behind one process-wide
//! lock (there is exactly one Flutter window driving it, so a single client is
//! assumed). No exported function crosses the C boundary with a panic: each
//! body runs inside [`std::panic::catch_unwind`] and turns a panic into an
//! ordinary error reply.
//!
//! Engine crates never depend on this crate, and nothing depends on it — it is
//! a leaf over `lumit-core`, `lumit-project` and (behind the default-on `media`
//! feature) `lumit-media` (docs/05-ARCHITECTURE.md). Behind the default-on
//! `render` feature it *also* borrows `lumit-ui`'s headless compositor for the
//! composited-comp Viewer path — the one deliberate, temporary exception, logged
//! as K-175: the bridge reaches into the UI crate's renderer through the
//! `lumit_render::headless` seam until the pixel pass moves into an engine crate.
//! The docs/05 rule (engine crates never depend on the UI) is unbroken; this is
//! the bridge, not an engine crate.
//!
//! ## Module map
//!
//! The crate is split so no one file grows unwieldy (owner's file-length
//! preference):
//! - [`state`] — the shared engine state and the v0.1/v0.2 state transitions
//!   (`String → String` JSON in, JSON out); this is where the core ops live.
//! - [`edits`] — the v0.3 edit ops: layer lifecycle, comp settings, keyframes,
//!   the work area and effects, split out to keep [`state`] under length.
//! - [`snapshot`] — turning a [`lumit_core::model::Document`] into the snapshot
//!   JSON the panels read (snapshot v3 adds the transform read-back, identity
//!   links, the work area and the effect stack to v2's comps/layers/media).
//! - [`media`] — probing footage and decoding frames, gated behind the `media`
//!   feature; plain-data probe results that the snapshot embeds either way.
//! - `render` — the composited-comp Viewer path, gated behind the `render`
//!   feature; holds one session-lifetime headless renderer borrowed from
//!   `lumit-ui` and turns `(comp, frame)` into an RGBA8 buffer (K-175).
//! - [`framecache`] — the rendered-frame cache (K-176): an LRU of RGBA frames
//!   keyed by comp/frame/scale under a document epoch, so a re-scrubbed frame
//!   skips the GPU. Its budget/clear/stats back the Settings → Performance cache
//!   controls; always compiled (inert without `render`, which is what fills it).
//! - [`cancel`] — engine-side render cancellation (K-176): a latest-wins
//!   generation high-water mark so a superseded comp render is skipped before it
//!   starts rather than stealing the renderer lock the next frame wants.
//! - [`ffi`] — the `extern "C"` surface: pointer marshalling, `catch_unwind`
//!   guards, and the string/buffer ownership contracts.

// flutter_rust_bridge's output, regenerated by `flutter_rust_bridge_codegen`
// whenever the `api` module changes — never edited by hand. It carries its own
// `#![allow(…)]` block for the style lints it trips, but not for the four panic
// lints this crate denies (docs/14 §4), so they are allowed here instead: an
// `#[allow]` on the `mod` item covers its contents, and putting it here rather
// than in the file means codegen cannot wipe it. The deny still applies in full
// to every hand-written module below.
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::unimplemented
)]
mod frb_generated;

// Pure defaults over lumit-core — no decoder, no GPU. It was gated on
// media+render when it also held the v0 ops that needed them.
mod edits;
mod export;
mod framecache;
mod media;
mod realtime;
#[cfg(feature = "render")]
mod render;

pub mod api;

use serde_json::json;

/// `{"ok":false,"error":"…"}`. serde escapes any control character, so the
/// resulting string never carries an interior NUL and always makes a `CString`.
pub(crate) fn err_json(message: impl AsRef<str>) -> String {
    json!({ "ok": false, "error": message.as_ref() }).to_string()
}
