// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The cache's live numbers.
///
/// Cheap enough to poll on the interface's own cadence — it reads five counters
/// behind one lock and renders nothing. It must never be called *per paint*
/// even so: the lock it takes is the one a render holds.
BridgeCacheStats cacheStats() =>
    BridgeLib.instance.api.crateApiCacheCacheStats();

/// Resize the cache, returning what it holds afterwards.
///
/// Shrinking evicts oldest-first straight away rather than waiting for the next
/// render, so the memory the user just asked to reclaim is actually gone when
/// the number on screen changes.
BridgeCacheStats setCacheBudget({required BigInt bytes}) =>
    BridgeLib.instance.api.crateApiCacheSetCacheBudget(bytes: bytes);

/// Empty the cache. Every frame is re-rendered from here on, so this is a
/// deliberate act rather than something to do on a timer.
BridgeCacheStats clearCache() =>
    BridgeLib.instance.api.crateApiCacheClearCache();

/// The VRAM cache's live numbers. `used`/`entries` are as the worker last
/// published (it holds the textures; nothing here touches the GPU); the
/// budget is the asked-for value, applied on the worker's next turn.
BridgeVramCacheStats vramCacheStats() =>
    BridgeLib.instance.api.crateApiCacheVramCacheStats();

/// Resize the VRAM cache. The worker applies it on its next turn, evicting
/// down immediately then; the returned stats show the new budget with the
/// holdings as last published.
BridgeVramCacheStats setVramCacheBudget({required BigInt bytes}) =>
    BridgeLib.instance.api.crateApiCacheSetVramCacheBudget(bytes: bytes);

/// Empty the VRAM cache on the worker's next turn.
BridgeVramCacheStats clearVramCache() =>
    BridgeLib.instance.api.crateApiCacheClearVramCache();

/// The disk tier's live numbers. `used`/`entries` are as the IO thread last
/// accounted them; the budget is the asked-for value, applied on the worker's
/// next turn.
BridgeDiskCacheStats diskCacheStats() =>
    BridgeLib.instance.api.crateApiCacheDiskCacheStats();

/// Resize the disk tier. Shrinking evicts oldest-first on the IO thread.
BridgeDiskCacheStats setDiskCacheBudget({required BigInt bytes}) =>
    BridgeLib.instance.api.crateApiCacheSetDiskCacheBudget(bytes: bytes);

/// Choose where parked frames live. `folder` is used only for
/// [`BridgeCacheLocation::Custom`] and ignored otherwise.
///
/// The worker re-opens the cache on its next turn: frames already parked
/// elsewhere are not moved or deleted — they are simply not addressed from the
/// new folder, and the old one can be deleted by hand at any time with no
/// correctness effect.
BridgeDiskCacheStats setDiskCacheLocation(
        {required BridgeCacheLocation location, required String folder}) =>
    BridgeLib.instance.api
        .crateApiCacheSetDiskCacheLocation(location: location, folder: folder);

/// Delete every parked frame, on the IO thread. Unlike the other two tiers this
/// destroys files that may represent hours of rendering and cannot be undone, so
/// the interface asks first (docs/07-UI-SPEC.md §15).
BridgeDiskCacheStats clearDiskCache() =>
    BridgeLib.instance.api.crateApiCacheClearDiskCache();

/// What this build compiles to. It reports the *build*, not the run — a machine
/// that cannot provide a shared texture still falls back at runtime.
BridgeViewerTransport viewerTransport() =>
    BridgeLib.instance.api.crateApiCacheViewerTransport();

/// Ask the render worker to measure what each frame costs, per layer and per
/// effect (docs/13 §7.1), or to stop.
///
/// **Not free, which is why it is a switch.** A measured frame waits for the
/// graphics card at every node, so a millisecond on a Timeline row means the
/// work rather than the paperwork — and that wait is exactly the overlap a
/// brisk preview lives on. So the numbers are collected while something is
/// showing them and not otherwise, and playback is never measured whatever
/// this says.
///
/// Takes effect from the next frame; frames already in flight finish as they
/// started.
void setRenderProfiling({required bool on_}) =>
    BridgeLib.instance.api.crateApiCacheSetRenderProfiling(on_: on_);

/// Where the disk tier keeps its frames (docs/07-UI-SPEC.md §15).
enum BridgeCacheLocation {
  /// Under the application's own cache folder, keyed by document id — the
  /// default, and the only one that works before a project has been saved.
  appData,

  /// In a `<project>.lum-cache/` folder beside the project file, so a project
  /// carries its cache with it. An unsaved project has nowhere to put one and
  /// falls back to [`Self::AppData`] until it is saved.
  besideProject,

  /// Under a folder the user picked — to park the cache on a faster or roomier
  /// drive. Application-wide.
  custom,
  ;
}

/// What the cache currently holds, for the Timeline's cache bar and the
/// Settings window's budget control.
class BridgeCacheStats {
  final BigInt usedBytes;
  final BigInt budgetBytes;
  final BigInt entries;

  /// Frames served from the cache rather than rendered.
  final BigInt hits;

  /// Frames that had to be rendered.
  final BigInt misses;

  /// Comp frames the worker's renderer has genuinely DECODED this session,
  /// as last mirrored. The drag fast path's meter: a value drag must not
  /// move it, so a decode that should not have happened is visible here
  /// rather than merely slow.
  final BigInt compDecodes;

  const BridgeCacheStats({
    required this.usedBytes,
    required this.budgetBytes,
    required this.entries,
    required this.hits,
    required this.misses,
    required this.compDecodes,
  });

  @override
  int get hashCode =>
      usedBytes.hashCode ^
      budgetBytes.hashCode ^
      entries.hashCode ^
      hits.hashCode ^
      misses.hashCode ^
      compDecodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCacheStats &&
          runtimeType == other.runtimeType &&
          usedBytes == other.usedBytes &&
          budgetBytes == other.budgetBytes &&
          entries == other.entries &&
          hits == other.hits &&
          misses == other.misses &&
          compDecodes == other.compDecodes;
}

/// What the disk tier holds — the bottom of the three-tier cache
/// (docs/06-RENDER-PIPELINE.md §5.4), and the only one that outlives the session.
class BridgeDiskCacheStats {
  final BigInt usedBytes;
  final BigInt budgetBytes;
  final BigInt entries;

  /// The folder the frames are actually going to, for Settings to show. Empty
  /// when the tier is off — which, since an unsaved project falls back to the
  /// application's own cache folder, means only a platform with no home
  /// directory at all.
  final String root;

  const BridgeDiskCacheStats({
    required this.usedBytes,
    required this.budgetBytes,
    required this.entries,
    required this.root,
  });

  @override
  int get hashCode =>
      usedBytes.hashCode ^
      budgetBytes.hashCode ^
      entries.hashCode ^
      root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDiskCacheStats &&
          runtimeType == other.runtimeType &&
          usedBytes == other.usedBytes &&
          budgetBytes == other.budgetBytes &&
          entries == other.entries &&
          root == other.root;
}

/// A cache location as a pair: which of the three, and the folder that goes with
/// `Custom` (empty for the other two).
///
/// The same shape whether it is being set for the application
/// ([`set_disk_cache_location`]) or for one project
/// (`ProjectReference::set_cache_location`), so the interface has one control and
/// one type for both, and the only difference is where the answer is stored.
class BridgeProjectCacheLocation {
  final BridgeCacheLocation location;
  final String folder;

  const BridgeProjectCacheLocation({
    required this.location,
    required this.folder,
  });

  @override
  int get hashCode => location.hashCode ^ folder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProjectCacheLocation &&
          runtimeType == other.runtimeType &&
          location == other.location &&
          folder == other.folder;
}

/// Which route a rendered frame takes from the engine to the Viewer.
///
/// Worth reporting rather than assuming: the zero-copy paths are build features,
/// and a build without one silently falls back. That fallback is four trips for
/// a picture that never needed to leave the graphics card — composite, copy down
/// to ordinary memory, serialise a byte at a time across the boundary, upload
/// back to the card to draw — so "which one am I on?" is the first question to
/// ask when playback feels heavy, and it should not need a rebuild to answer.
enum BridgeViewerTransport {
  /// Windows: a D3D12 texture shared by handle. No pixels cross.
  sharedTexture,

  /// Linux: a DMA-BUF shared by file descriptor. No pixels cross.
  dmaBuf,

  /// Every pixel copied down, serialised, and uploaded again.
  readBack,
  ;
}

/// What the VRAM final-frame cache holds — the tier that makes a revisited
/// frame free on the zero-copy Viewer ("cache on the card", docs/06 §5.1).
class BridgeVramCacheStats {
  final BigInt usedBytes;
  final BigInt budgetBytes;
  final BigInt entries;

  const BridgeVramCacheStats({
    required this.usedBytes,
    required this.budgetBytes,
    required this.entries,
  });

  @override
  int get hashCode =>
      usedBytes.hashCode ^ budgetBytes.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeVramCacheStats &&
          runtimeType == other.runtimeType &&
          usedBytes == other.usedBytes &&
          budgetBytes == other.budgetBytes &&
          entries == other.entries;
}
