// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'effect.dart';
import 'footage.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `composition`, `dispatch`, `footage_span_and_size`, `project`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `id`, `new`, `project_id`

/// Everything the Composition settings dialog reads and writes.
///
/// The frame rate is the exact `num`/`den` pair and the duration is a frame count,
/// never floating-point seconds (docs/14 §2). A dialog that round-tripped 29.97
/// through a double would not hand it back as 30000/1001.
class BridgeCompSettings {
  final String name;
  final int width;
  final int height;
  final int fpsNum;
  final int fpsDen;
  final PlatformInt64 durationFrames;

  const BridgeCompSettings({
    required this.name,
    required this.width,
    required this.height,
    required this.fpsNum,
    required this.fpsDen,
    required this.durationFrames,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fpsNum.hashCode ^
      fpsDen.hashCode ^
      durationFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompSettings &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          fpsNum == other.fpsNum &&
          fpsDen == other.fpsDen &&
          durationFrames == other.durationFrames;
}

/// A composition's pixel dimensions.
class BridgeCompSize {
  final int width;
  final int height;

  const BridgeCompSize({
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

class CompositionReference {
  final UuidValue internalproject;
  final UuidValue internalid;

  const CompositionReference({
    required this.internalproject,
    required this.internalid,
  });

  /// Place `footage` into this composition as a new top layer.
  ///
  /// The layer's span is the media's own duration in comp frames, and its
  /// transform is anchored on the media's own centre at the comp centre (K-150),
  /// so a placed clip appears centred and pivots about its middle. Both fall
  /// back to the comp's duration and size when the media cannot be probed —
  /// a missing file still places, so the user can relink it rather than being
  /// unable to add it at all.
  ///
  /// The duration comes from the container's real `duration_seconds`, not from
  /// a frame count: audio-only media has no video frame count or rate, and
  /// reconstructing seconds from those silently clamped such a clip to one frame.
  void addFootageLayer({required FootageReference footage}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddFootageLayer(
              that: this, footage: footage);

  /// The frame containing `time` (floored) — the inverse of
  /// [`Self::time_of_frame`], for drawing a key at a frame position.
  PlatformInt64 frameAtTime({required BridgeRational time}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceFrameAtTime(
          that: this, time: time);

  List<LayerReference> getLayers() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetLayers(
        that: this,
      );

  /// Everything the Composition settings dialog shows.
  ///
  /// The frame rate crosses as an exact `{num, den}` pair and the duration as a
  /// frame count, never as floating-point seconds — docs/14 §2's rational-time
  /// rule. 29.97 fps is 30000/1001, and a dialog that round-tripped it through a
  /// double would not give it back.
  BridgeCompSettings getSettings() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetSettings(
        that: this,
      );

  /// The comp's pixel dimensions. The Viewer needs these to work out what
  /// fraction of comp resolution it is actually showing, which is the `scale`
  /// every render request carries — without them it could only ever ask for
  /// full resolution.
  BridgeCompSize getSize() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetSize(
        that: this,
      );

  /// Ask for `frame` at `scale` — 1.0 meaning "shown at comp resolution".
  /// Below 1.0 the engine decodes and composites smaller, which is how a
  /// Viewer that is not filling the screen stays cheap.
  void renderFrame({required BigInt frame, required double scale}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceRenderFrame(
          that: this, frame: frame, scale: scale);

  /// Ask for `frame` with `layer`'s effect stack replaced by `effects` — the
  /// live drag path, which never touches the document.
  void renderFrameWithPreview(
          {required BigInt frame,
          required double scale,
          required LayerReference layer,
          required List<BridgeEffectInstance> effects}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceRenderFrameWithPreview(
              that: this,
              frame: frame,
              scale: scale,
              layer: layer,
              effects: effects);

  /// Ask for `frame` with `layer`'s transform replaced by `transform` — the
  /// same live-drag path as [`Self::render_frame_with_preview`], for the
  /// Transform rows. Never touches the document.
  void renderFrameWithTransformPreview(
          {required BigInt frame,
          required double scale,
          required LayerReference layer,
          required BridgeTransform transform}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceRenderFrameWithTransformPreview(
              that: this,
              frame: frame,
              scale: scale,
              layer: layer,
              transform: transform);

  /// Apply the Composition settings dialog, as one undo step.
  ///
  /// Dimensions are clamped to 16..=16384 and the duration to at least one frame,
  /// so a dialog cannot commit a comp that is zero pixels wide or zero frames
  /// long. The background colour is preserved: it is not part of this dialog, and
  /// `SetCompSettings` carries the whole settings block.
  void setSettings({required BridgeCompSettings settings}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceSetSettings(
          that: this, settings: settings);

  /// The exact time frame `frame` starts at, as the rational the document
  /// stores.
  ///
  /// Exposed rather than left to Dart because keyframe times must be exact
  /// (docs/14 §2): at 29.97 fps a frame is 1001/30000 s, and a panel that
  /// worked that out in floating point would place keys that do not land on
  /// the frame they were set on. This is the engine's own
  /// `FrameRate::time_of_frame`, so there is one implementation of it.
  BridgeRational timeOfFrame({required PlatformInt64 frame}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceTimeOfFrame(
          that: this, frame: frame);

  @override
  int get hashCode => internalproject.hashCode ^ internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompositionReference &&
          runtimeType == other.runtimeType &&
          internalproject == other.internalproject &&
          internalid == other.internalid;
}
