// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'effect.dart';
import 'export.dart';
import 'footage.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `add_at_top`, `commit`, `composition`, `dispatch`, `document`, `footage_span_and_size`, `project`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `id`, `new`, `project_id`

/// Every blend mode, in the order the Timeline's dropdown shows them. The index
/// into this list is what `LayerReference::get_blend`/`set_blend` speak, so the
/// two cannot disagree about what "3" means.
///
/// Stateless, so a free function: the dropdown is built before any layer is
/// selected.
List<String> listBlendModes() =>
    BridgeLib.instance.api.crateApiCompositionListBlendModes();

/// Everything the Composition settings dialog reads and writes.
///
/// The frame rate is the exact `num`/`den` pair and the duration is a frame count,
/// never floating-point seconds (docs/14 §2). A dialog that round-tripped 29.97
/// through a double would not hand it back as 30000/1001.
class BridgeCompSettings {
  final String name;
  final int width;
  final int height;
  final int fpsNum;
  final int fpsDen;
  final PlatformInt64 durationFrames;

  const BridgeCompSettings({
    required this.name,
    required this.width,
    required this.height,
    required this.fpsNum,
    required this.fpsDen,
    required this.durationFrames,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fpsNum.hashCode ^
      fpsDen.hashCode ^
      durationFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompSettings &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          fpsNum == other.fpsNum &&
          fpsDen == other.fpsDen &&
          durationFrames == other.durationFrames;
}

/// A composition's pixel dimensions.
class BridgeCompSize {
  final int width;
  final int height;

  const BridgeCompSize({
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCompSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

/// One timeline marker (docs/03 §11): a cue on the comp's timebase.
///
/// The engine's marker also carries a duration and a kind; neither has a
/// control yet, so they are not carried across — a marker written back keeps
/// what the panel can actually edit and does not pretend to round-trip the rest.
class BridgeMarker {
  final UuidValue id;
  final BridgeRational time;
  final String label;

  const BridgeMarker({
    required this.id,
    required this.time,
    required this.label,
  });

  @override
  int get hashCode => id.hashCode ^ time.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMarker &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          time == other.time &&
          label == other.label;
}

class CompositionReference {
  final UuidValue internalproject;
  final UuidValue internalid;

  const CompositionReference({
    required this.internalproject,
    required this.internalid,
  });

  /// Add an Adjustment layer: a comp-sized effect container with no source of
  /// its own, centred so scale and rotation pivot about the middle.
  LayerReference addAdjustmentLayer() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddAdjustmentLayer(
        that: this,
      );

  /// Add a Camera layer at the comp centre. The default zoom is the After
  /// Effects 50 mm model, `comp width × 50/36`.
  LayerReference addCameraLayer() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddCameraLayer(
        that: this,
      );

  /// Place `footage` into this composition as a new top layer.
  ///
  /// The layer's span is the media's own duration in comp frames, and its
  /// transform is anchored on the media's own centre at the comp centre (K-150),
  /// so a placed clip appears centred and pivots about its middle. Both fall
  /// back to the comp's duration and size when the media cannot be probed —
  /// a missing file still places, so the user can relink it rather than being
  /// unable to add it at all.
  ///
  /// The duration comes from the container's real `duration_seconds`, not from
  /// a frame count: audio-only media has no video frame count or rate, and
  /// reconstructing seconds from those silently clamped such a clip to one frame.
  void addFootageLayer({required FootageReference footage}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddFootageLayer(
              that: this, footage: footage);

  /// Place another composition into this one as a Precomp layer.
  ///
  /// Refuses to nest a comp inside itself. A deeper cycle — A inside B inside
  /// A — is not checked here, because doing it properly means walking the
  /// whole tree on every insertion; the render guards defensively against one
  /// and the Hierarchy panel bounds its own recursion. The one-step case is
  /// checked because it is the one a user reaches by accident.
  LayerReference addPrecompLayer({required CompositionReference comp}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddPrecompLayer(
              that: this, comp: comp);

  /// Add an empty Sequence layer — a clip row spanning the comp.
  LayerReference addSequenceLayer() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddSequenceLayer(
        that: this,
      );

  /// Add a Solid layer backed by a fresh SolidDef filed in the Solids
  /// auto-folder — one batch, one undo step, matching the egui frontend. The
  /// solid is comp-sized and white, named "White solid N".
  LayerReference addSolidLayer() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddSolidLayer(
        that: this,
      );

  /// Add a Text layer with the "Text" starter document, centred.
  LayerReference addTextLayer() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAddTextLayer(
        that: this,
      );

  /// Start playing this comp's audio from `start` seconds.
  void audioPlay({required double start}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceAudioPlay(
          that: this, start: start);

  /// Build or refresh this comp's mix in the background.
  ///
  /// Call it after an edit while audio is loaded or playing. An edit that does
  /// not change what the comp sounds like — moving a silent layer, renaming
  /// something — is recognised by a signature and costs nothing.
  void audioPrepare() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceAudioPrepare(
        that: this,
      );

  /// Remove every detected beat marker, keeping the ones a person made.
  ///
  /// A comp with none is a calm no-op rather than an error — clearing twice is
  /// something a user does without thinking about it.
  void clearBeatMarkers() => BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceClearBeatMarkers(
        that: this,
      );

  /// Detect beats and replace this comp's beat markers.
  ///
  /// `sensitivity_percent` runs 0..100, where 50 is the standard setting and
  /// higher finds more. Returns how many markers were placed — zero is a
  /// legitimate answer for quiet or arrhythmic audio, and worth showing as
  /// such rather than as a failure.
  int detectBeats({required int sensitivityPercent}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceDetectBeats(
          that: this, sensitivityPercent: sensitivityPercent);

  /// The frame containing `time` (floored) — the inverse of
  /// [`Self::time_of_frame`], for drawing a key at a frame position.
  PlatformInt64 frameAtTime({required BridgeRational time}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceFrameAtTime(
          that: this, time: time);

  List<LayerReference> getLayers() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetLayers(
        that: this,
      );

  /// Every marker on this comp, in the order the document holds them.
  List<BridgeMarker> getMarkers() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetMarkers(
        that: this,
      );

  /// Everything the Composition settings dialog shows.
  ///
  /// The frame rate crosses as an exact `{num, den}` pair and the duration as a
  /// frame count, never as floating-point seconds — docs/14 §2's rational-time
  /// rule. 29.97 fps is 30000/1001, and a dialog that round-tripped it through a
  /// double would not give it back.
  BridgeCompSettings getSettings() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetSettings(
        that: this,
      );

  /// The comp's pixel dimensions. The Viewer needs these to work out what
  /// fraction of comp resolution it is actually showing, which is the `scale`
  /// every render request carries — without them it could only ever ask for
  /// full resolution.
  BridgeCompSize getSize() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetSize(
        that: this,
      );

  /// The comp's work area — the span the Viewer previews and the export
  /// writes — or `None` for the whole comp.
  BridgeSpan? getWorkArea() =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceGetWorkArea(
        that: this,
      );

  /// Ask for `frame` at `scale` — 1.0 meaning "shown at comp resolution".
  /// Below 1.0 the engine decodes and composites smaller, which is how a
  /// Viewer that is not filling the screen stays cheap.
  void renderFrame({required BigInt frame, required double scale}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceRenderFrame(
          that: this, frame: frame, scale: scale);

  /// Ask for `frame` with `layer`'s effect stack replaced by `effects` — the
  /// live drag path, which never touches the document.
  void renderFrameWithPreview(
          {required BigInt frame,
          required double scale,
          required LayerReference layer,
          required List<BridgeEffectInstance> effects}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceRenderFrameWithPreview(
              that: this,
              frame: frame,
              scale: scale,
              layer: layer,
              effects: effects);

  /// Ask for `frame` with `layer`'s transform replaced by `transform` — the
  /// same live-drag path as [`Self::render_frame_with_preview`], for the
  /// Transform rows. Never touches the document.
  void renderFrameWithTransformPreview(
          {required BigInt frame,
          required double scale,
          required LayerReference layer,
          required BridgeTransform transform}) =>
      BridgeLib.instance.api
          .crateApiCompositionCompositionReferenceRenderFrameWithTransformPreview(
              that: this,
              frame: frame,
              scale: scale,
              layer: layer,
              transform: transform);

  /// Ask the worker for a scope trace of `frame`.
  ///
  /// `kind` is the trace: 0 waveform, 1 parade, 2 vectorscope, 3 histogram.
  /// `colours` is background, trace, then the R, G and B tints, each as
  /// `[r, g, b]` — the panel's theme decides them, so the engine never has to
  /// know what a Lumit surface looks like.
  void renderScope(
          {required BigInt frame,
          required double scale,
          required int kind,
          required List<Uint8List> colours}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceRenderScope(
          that: this, frame: frame, scale: scale, kind: kind, colours: colours);

  /// Replace the whole marker list — one op, trivially invertible, which is
  /// also how beat detection commits a regenerated set.
  void setMarkers({required List<BridgeMarker> markers}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceSetMarkers(
          that: this, markers: markers);

  /// Apply the Composition settings dialog, as one undo step.
  ///
  /// Dimensions are clamped to 16..=16384 and the duration to at least one frame,
  /// so a dialog cannot commit a comp that is zero pixels wide or zero frames
  /// long. The background colour is preserved: it is not part of this dialog, and
  /// `SetCompSettings` carries the whole settings block.
  void setSettings({required BridgeCompSettings settings}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceSetSettings(
          that: this, settings: settings);

  /// Set the work area, or clear it with `None`.
  void setWorkArea({BridgeSpan? span}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceSetWorkArea(
          that: this, span: span);

  /// Start writing this composition to `path`.
  ///
  /// Returns once the job is *running*, not once it is finished — ask
  /// [`export_poll`] for that. An export already in flight is a calm error.
  void startExport({required BridgeExportSpec spec, required String path}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceStartExport(
          that: this, spec: spec, path: path);

  /// The exact time frame `frame` starts at, as the rational the document
  /// stores.
  ///
  /// Exposed rather than left to Dart because keyframe times must be exact
  /// (docs/14 §2): at 29.97 fps a frame is 1001/30000 s, and a panel that
  /// worked that out in floating point would place keys that do not land on
  /// the frame they were set on. This is the engine's own
  /// `FrameRate::time_of_frame`, so there is one implementation of it.
  BridgeRational timeOfFrame({required PlatformInt64 frame}) =>
      BridgeLib.instance.api.crateApiCompositionCompositionReferenceTimeOfFrame(
          that: this, frame: frame);

  @override
  int get hashCode => internalproject.hashCode ^ internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompositionReference &&
          runtimeType == other.runtimeType &&
          internalproject == other.internalproject &&
          internalid == other.internalid;
}
