// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_effects`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeEffectInstance>>
abstract class BridgeEffectInstance implements RustOpaqueInterface {
  List<String> getParameters();

  double getValue({required String id});

  String name();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BridgeEffectInstance> newInstance(
          {required EffectInstance effect}) =>
      BridgeLib.instance.api
          .crateApiEffectBridgeEffectInstanceNew(effect: effect);

  String serialize();

  void setValue({required String id, required double value});
}
