// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'export.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `reply_error`, `reply_ok`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// How the running export is getting on. Safe to call on the interface's own
/// cadence: it drains a channel and reads a few numbers.
BridgeExportState exportPoll() =>
    BridgeLib.instance.api.crateApiExportExportPoll();

/// Ask the running export to stop. It finishes the frame it is on and then
/// reports `Failed` with "cancelled" — a cancelled export leaves no half-file
/// pretending to be a finished one.
void exportCancel() => BridgeLib.instance.api.crateApiExportExportCancel();

/// What the export dialogue is asking for.
///
/// `width`/`height` of zero mean "the composition's own size", which is what the
/// dialogue shows until somebody types over it. `bitrate_mbps` of zero means the
/// encoder's own default — a quality nobody chose is better than a number this
/// layer invented.
class BridgeExportSpec {
  /// A delivery preset name, or empty for a custom export.
  final String preset;

  /// The video codec key, e.g. `h264`.
  final String codec;
  final int width;
  final int height;
  final int bitrateMbps;
  final bool includeAudio;

  /// Audio bits per second; zero takes the preset's own rate.
  final PlatformInt64 audioBitRate;

  const BridgeExportSpec({
    required this.preset,
    required this.codec,
    required this.width,
    required this.height,
    required this.bitrateMbps,
    required this.includeAudio,
    required this.audioBitRate,
  });

  @override
  int get hashCode =>
      preset.hashCode ^
      codec.hashCode ^
      width.hashCode ^
      height.hashCode ^
      bitrateMbps.hashCode ^
      includeAudio.hashCode ^
      audioBitRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeExportSpec &&
          runtimeType == other.runtimeType &&
          preset == other.preset &&
          codec == other.codec &&
          width == other.width &&
          height == other.height &&
          bitrateMbps == other.bitrateMbps &&
          includeAudio == other.includeAudio &&
          audioBitRate == other.audioBitRate;
}

@freezed
sealed class BridgeExportState with _$BridgeExportState {
  const BridgeExportState._();

  /// Nothing has run since start-up.
  const factory BridgeExportState.idle() = BridgeExportState_Idle;
  const factory BridgeExportState.running({
    required BigInt frame,

    /// Zero until the exporter has worked out how many there are.
    required BigInt total,

    /// The encoder actually chosen, which may not be the one asked for —
    /// a hardware encoder that is not there falls back to software, and the
    /// dialogue should say so rather than claim what was requested.
    required String encoder,
  }) = BridgeExportState_Running;
  const factory BridgeExportState.done({
    required String path,
  }) = BridgeExportState_Done;
  const factory BridgeExportState.failed({
    required String error,
  }) = BridgeExportState_Failed;
}
