// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `footage_path`, `project`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `id`, `new`, `project_id`

class FootageReference {
  final UuidValue internalproject;
  final UuidValue internalid;

  const FootageReference({
    required this.internalproject,
    required this.internalid,
  });

  Future<LumitMediaStatus> getStatus() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceGetStatus(
        that: this,
      );

  @override
  int get hashCode => internalproject.hashCode ^ internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FootageReference &&
          runtimeType == other.runtimeType &&
          internalproject == other.internalproject &&
          internalid == other.internalid;
}

enum LumitMediaStatus {
  missing,
  ready,
  ;
}
