// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'state.dart';

// These functions are ignored because they are not marked as `pub`: `project`, `resolve_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `id`, `new`, `project_id`

class FootageReference {
  final UuidValue internalproject;
  final UuidValue internalid;

  const FootageReference({
    required this.internalproject,
    required this.internalid,
  });

  Future<LumitMediaStatus> getStatus() =>
      BridgeLib.instance.api.crateApiFootageFootageReferenceGetStatus(
        that: this,
      );

  /// Point this footage item at `path`, and fix every *other* missing item
  /// whose file name turns up in the same folder — one undo step for the lot.
  ///
  /// The sibling sweep is the behaviour that makes relinking a moved project
  /// bearable: footage almost always moves as a folder, so relinking one clip
  /// by hand should not mean relinking forty. A sibling is only touched when it
  /// currently fails to resolve *and* a file of its name exists beside the
  /// picked one, so a healthy item is never repointed.
  void relink({required String path}) => BridgeLib.instance.api
      .crateApiFootageFootageReferenceRelink(that: this, path: path);

  Future<BridgeRenderedFrame?> thumbnail({required int maxEdge}) => BridgeLib
      .instance.api
      .crateApiFootageFootageReferenceThumbnail(that: this, maxEdge: maxEdge);

  @override
  int get hashCode => internalproject.hashCode ^ internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FootageReference &&
          runtimeType == other.runtimeType &&
          internalproject == other.internalproject &&
          internalid == other.internalid;
}

enum LumitMediaStatus {
  missing,
  ready,
  ;
}
