// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'effect.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `item`, `project`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `comp_id`, `id`, `new`, `project_id`

class LayerReference {
  final UuidValue internalprojectId;
  final UuidValue internalcompId;
  final UuidValue internallayerId;

  const LayerReference({
    required this.internalprojectId,
    required this.internalcompId,
    required this.internallayerId,
  });

  bool equals({required LayerReference layer}) => BridgeLib.instance.api
      .crateApiLayerLayerReferenceEquals(that: this, layer: layer);

  List<BridgeEffectInstance> getEffects() =>
      BridgeLib.instance.api.crateApiLayerLayerReferenceGetEffects(
        that: this,
      );

  String getName() => BridgeLib.instance.api.crateApiLayerLayerReferenceGetName(
        that: this,
      );

  void rename({required String name}) => BridgeLib.instance.api
      .crateApiLayerLayerReferenceRename(that: this, name: name);

  @override
  int get hashCode =>
      internalprojectId.hashCode ^
      internalcompId.hashCode ^
      internallayerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayerReference &&
          runtimeType == other.runtimeType &&
          internalprojectId == other.internalprojectId &&
          internalcompId == other.internalcompId &&
          internallayerId == other.internallayerId;
}
