// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'effect.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `composition`, `core`, `item`, `project`, `read`, `with_effects`, `write`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `comp_id`, `id`, `new`, `project_id`

/// A layer's whole transform, one scalar per property.
///
/// Read as a group rather than a property at a time because the panel draws them
/// as a group and a drag on one axis previews the others unchanged — eleven
/// round trips per frame to rebuild what one call already has would be the
/// snapshot habit creeping back in. Writing is per-property (see
/// [`LayerReference::set_transform`]), which is what keeps each edit exactly
/// invertible.
class BridgeTransform {
  final BridgeScalar anchorX;
  final BridgeScalar anchorY;
  final BridgeScalar positionX;
  final BridgeScalar positionY;

  /// The 2.5D depth (K-023). Present on every layer; only meaningful, and only
  /// drawn, when the layer's 3D switch is on.
  final BridgeScalar positionZ;

  /// Percent, 100 = natural size.
  final BridgeScalar scaleX;
  final BridgeScalar scaleY;

  /// Degrees, about z — the 2D rotation.
  final BridgeScalar rotation;
  final BridgeScalar rotationX;
  final BridgeScalar rotationY;

  /// Percent, 0..100.
  final BridgeScalar opacity;

  const BridgeTransform({
    required this.anchorX,
    required this.anchorY,
    required this.positionX,
    required this.positionY,
    required this.positionZ,
    required this.scaleX,
    required this.scaleY,
    required this.rotation,
    required this.rotationX,
    required this.rotationY,
    required this.opacity,
  });

  @override
  int get hashCode =>
      anchorX.hashCode ^
      anchorY.hashCode ^
      positionX.hashCode ^
      positionY.hashCode ^
      positionZ.hashCode ^
      scaleX.hashCode ^
      scaleY.hashCode ^
      rotation.hashCode ^
      rotationX.hashCode ^
      rotationY.hashCode ^
      opacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTransform &&
          runtimeType == other.runtimeType &&
          anchorX == other.anchorX &&
          anchorY == other.anchorY &&
          positionX == other.positionX &&
          positionY == other.positionY &&
          positionZ == other.positionZ &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          rotation == other.rotation &&
          rotationX == other.rotationX &&
          rotationY == other.rotationY &&
          opacity == other.opacity;
}

/// Which transform property an edit names ([`lumit_core::model::TransformProp`]).
enum BridgeTransformProp {
  anchorX,
  anchorY,
  positionX,
  positionY,
  positionZ,
  scaleX,
  scaleY,
  rotation,
  rotationX,
  rotationY,
  opacity,
  ;
}

class LayerReference {
  final UuidValue internalprojectId;
  final UuidValue internalcompId;
  final UuidValue internallayerId;

  const LayerReference({
    required this.internalprojectId,
    required this.internalcompId,
    required this.internallayerId,
  });

  /// Append the built-in effect named `name` to this layer's stack.
  ///
  /// Seeded at composition size, because a few effects' defaults are positions
  /// (a transform's anchor and position start at the centre of the frame), and
  /// a fresh effect should look like identity rather than dragging the picture
  /// to a corner. An unknown name is refused; nothing partial is committed.
  void addEffect({required String name}) => BridgeLib.instance.api
      .crateApiLayerLayerReferenceAddEffect(that: this, name: name);

  bool equals({required LayerReference layer}) => BridgeLib.instance.api
      .crateApiLayerLayerReferenceEquals(that: this, layer: layer);

  List<BridgeEffectInstance> getEffects() =>
      BridgeLib.instance.api.crateApiLayerLayerReferenceGetEffects(
        that: this,
      );

  String getName() => BridgeLib.instance.api.crateApiLayerLayerReferenceGetName(
        that: this,
      );

  /// This layer's whole transform.
  BridgeTransform getTransform() =>
      BridgeLib.instance.api.crateApiLayerLayerReferenceGetTransform(
        that: this,
      );

  /// Whether this layer positions in z and honours the active camera (K-023).
  ///
  /// Read-only for now: the switch's *toggle* is a Timeline op that has not
  /// been ported. The Effect controls panel needs the reader regardless, to
  /// decide whether to draw the z and x/y-rotation rows at all — a 2D layer
  /// showing 3D controls that do nothing is worse than not showing them. A
  /// camera is 3D by construction whatever its switch says.
  bool isThreeD() => BridgeLib.instance.api.crateApiLayerLayerReferenceIsThreeD(
        that: this,
      );

  /// Remove `effect` from this layer's stack. An effect that is no longer there
  /// is an error rather than a silent success, so a double-click on Remove
  /// cannot look as though it deleted a second effect.
  void removeEffect({required BridgeEffectInstance effect}) =>
      BridgeLib.instance.api
          .crateApiLayerLayerReferenceRemoveEffect(that: this, effect: effect);

  void rename({required String name}) => BridgeLib.instance.api
      .crateApiLayerLayerReferenceRename(that: this, name: name);

  /// Move `effect` to `new_index` in the stack — drag-to-reorder.
  ///
  /// The index clamps into range rather than failing: past the end lands the
  /// effect at the bottom, negative lands it at the top. A drag that overshoots
  /// the list is an ordinary thing for a pointer to do, and refusing it would
  /// leave the effect where it started with no explanation.
  void reorderEffect(
          {required BridgeEffectInstance effect,
          required PlatformInt64 newIndex}) =>
      BridgeLib.instance.api.crateApiLayerLayerReferenceReorderEffect(
          that: this, effect: effect, newIndex: newIndex);

  /// Enable or bypass `effect`. A bypassed effect renders as identity and is
  /// not animatable (docs/08 §1.5 — the effect's own Mix parameter is the
  /// animatable dial).
  void setEffectEnabled(
          {required BridgeEffectInstance effect, required bool enabled}) =>
      BridgeLib.instance.api.crateApiLayerLayerReferenceSetEffectEnabled(
          that: this, effect: effect, enabled: enabled);

  /// Commit a staged effect stack — the mouse-up for a gesture Dart has been
  /// editing through `BridgeEffectInstance::set_value` and previewing through
  /// `CompositionReference::render_frame_with_preview`. The whole drag becomes
  /// one undo step, which is the entire point of staging (docs/17 ABI v12).
  ///
  /// Only parameter *values* may cross this way: the staged stack must still
  /// name the same effects, in the same order, as the document does. Otherwise
  /// a stack read before some other action removed an effect from it would
  /// resurrect that effect on mouse-up, and reordering or deleting would have
  /// two paths — this one, which cannot say what it meant, and the dedicated
  /// ops above, which can.
  void setEffects({required List<BridgeEffectInstance> effects}) =>
      BridgeLib.instance.api
          .crateApiLayerLayerReferenceSetEffects(that: this, effects: effects);

  /// Replace one transform property's whole animation, as one
  /// [`lumit_core::Op::SetTransformProperty`].
  ///
  /// One property per op, not the whole group: the op is exactly invertible
  /// that way, so a nudged Position is one undo step that puts back precisely
  /// what was there — where committing all eleven would make undo restore ten
  /// properties nobody touched.
  void setTransform(
          {required BridgeTransformProp prop, required BridgeScalar value}) =>
      BridgeLib.instance.api.crateApiLayerLayerReferenceSetTransform(
          that: this, prop: prop, value: value);

  @override
  int get hashCode =>
      internalprojectId.hashCode ^
      internalcompId.hashCode ^
      internallayerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LayerReference &&
          runtimeType == other.runtimeType &&
          internalprojectId == other.internalprojectId &&
          internalcompId == other.internalcompId &&
          internallayerId == other.internallayerId;
}
