// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'solid.dart';
part 'project_item.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `commit`, `item_id`, `item_reference`, `item`, `project_id`, `project`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LumitProjectItemInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `eq`, `fmt`

@freezed
sealed class ItemReference with _$ItemReference {
  const ItemReference._();

  const factory ItemReference.footage(
    FootageReference field0,
  ) = ItemReference_Footage;
  const factory ItemReference.solid(
    SolidReference field0,
  ) = ItemReference_Solid;
  const factory ItemReference.composition(
    CompositionReference field0,
  ) = ItemReference_Composition;
  const factory ItemReference.folder(
    FolderReference field0,
  ) = ItemReference_Folder;

  /// Delete the item. One undo step, no confirmation — matching the egui
  /// project menu, where Delete is undoable and therefore not worth a dialog.
  void delete() =>
      BridgeLib.instance.api.crateApiProjectItemItemReferenceDelete(
        that: this,
      );

  bool equals({required ItemReference item}) => BridgeLib.instance.api
      .crateApiProjectItemItemReferenceEquals(that: this, item: item);

  /// Move the item back to the panel root: remove it from every folder that
  /// lists it, as one undo step. Already at the root is a calm no-op.
  void moveToRoot() =>
      BridgeLib.instance.api.crateApiProjectItemItemReferenceMoveToRoot(
        that: this,
      );

  String name() => BridgeLib.instance.api.crateApiProjectItemItemReferenceName(
        that: this,
      );

  /// Rename the item — the panel's in-place rename.
  ///
  /// A blank name is refused rather than applied, matching v0: the field keeps
  /// the old name instead of the row losing its label.
  void rename({required String name}) => BridgeLib.instance.api
      .crateApiProjectItemItemReferenceRename(that: this, name: name);
}
