// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'cache.dart';
import 'composition.dart';
import 'effect.dart';
import 'folder.dart';
import 'footage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'project_item.dart';
import 'shell.dart';
import 'solid.dart';
import 'state.dart';

// These functions are ignored because they are not marked as `pub`: `next_comp_name_in`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`, `state`

/// Whether undo and redo have anything to do, for greying the menu items.
class BridgeHistory {
  final bool canUndo;
  final bool canRedo;

  const BridgeHistory({
    required this.canUndo,
    required this.canRedo,
  });

  @override
  int get hashCode => canUndo.hashCode ^ canRedo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistory &&
          runtimeType == other.runtimeType &&
          canUndo == other.canUndo &&
          canRedo == other.canRedo;
}

class ProjectReference {
  final UuidValue internalid;

  const ProjectReference({
    required this.internalid,
  });

  /// Write a rotating autosave beside `project_path`, keeping `keep` slots.
  ///
  /// Deliberately does **not** move the project's own path: an autosave is a
  /// safety copy, and the next Save must still write the file the user chose.
  /// The document is rebased against the project folder first, so no
  /// machine-specific path is written into a copy that may be opened
  /// elsewhere.
  String autosave({required String projectPath, required int keep}) =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceAutosave(
          that: this, projectPath: projectPath, keep: keep);

  /// Where *this project* parks its rendered frames, overriding the
  /// application-wide choice — or `None` when it follows that choice, which is
  /// the ordinary case (docs/06-RENDER-PIPELINE.md §5.4).
  ///
  /// Returned as the enum plus a folder, the same pair
  /// [`Self::set_cache_location`] takes; the folder is empty unless the
  /// location is `Custom`.
  BridgeProjectCacheLocation? cacheLocation() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceCacheLocation(
        that: this,
      );

  List<ItemReference> getItems() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceGetItems(
        that: this,
      );

  /// Whether there is anything to undo or redo, for greying the menu items.
  BridgeHistory history() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceHistory(
        that: this,
      );

  /// Record `path` as a footage item, as one undo step.
  ///
  /// Importing only *records* the file — it does not decode it or read its size.
  /// Footage has no auto-folder (only solids and comps do), so the item lands at
  /// the panel root, matching the egui frontend exactly.
  ///
  /// The bare file name becomes the relative path; saving rebases it against the
  /// project folder (K-173).
  FootageReference importFootage({required String path}) =>
      BridgeLib.instance.api
          .crateApiProjectProjectReferenceImportFootage(that: this, path: path);

  /// Whether the document has moved since it was last saved (or opened).
  /// The status bar's saved/unsaved readout. An undo after a save reads as
  /// dirty: the revision moved, and only a save proves the file matches.
  bool isDirty() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceIsDirty(
        that: this,
      );

  /// Add a composition, filed into the Compositions auto-folder, as one undo
  /// step. A blank name gets the next "Comp N".
  ///
  /// `settings` is what the New composition dialog collected — size, rate and
  /// duration. `None` takes the defaults ([`BridgeCompSettings::defaults`]), which
  /// is what every caller that does not ask the user does. `settings.name` is
  /// ignored: the name comes from `name`, so there is one answer to "what is this
  /// comp called" rather than two that can disagree.
  ///
  /// It is one call rather than "create, then apply settings" because that would
  /// be two undo steps for one click, and undoing once would leave a comp behind
  /// at the wrong size.
  ///
  /// The folder is tracked by id, not by name, so renaming or nesting it keeps
  /// it the Compositions folder — the same habit the egui frontend has.
  CompositionReference newComposition(
          {required String name, BridgeCompSettings? settings}) =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceNewComposition(
          that: this, name: name, settings: settings);

  /// The name a comp made right now would get, if nobody typed one — "Comp 3"
  /// when the project holds two. What the New composition dialog puts in its
  /// Name field before the user touches it, so the field shows the same name
  /// the engine would have chosen rather than a guess made in Dart.
  String nextCompName() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceNextCompName(
        that: this,
      );

  /// Where this project was last saved, or null when it never has been. The
  /// menu bar needs it to decide between Save and Save as.
  String? path() => BridgeLib.instance.api.crateApiProjectProjectReferencePath(
        that: this,
      );

  void redo() => BridgeLib.instance.api.crateApiProjectProjectReferenceRedo(
        that: this,
      );

  /// Open `project_path` and replay its crash journal on top of it.
  ///
  /// This is the whole point of the journal: a session that ended badly left
  /// its edits there, and this is what puts them back. The replay stops at the
  /// first op that no longer applies — see [`BridgeRecovery::replayed`].
  BridgeRecovery restoreJournal({required String projectPath}) =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceRestoreJournal(
          that: this, projectPath: projectPath);

  /// Save to `path`, or to wherever the project was last saved when `path` is
  /// empty. Answers the path actually written, so Dart can show it and stop
  /// asking where to put the file.
  ///
  /// Deliberately **not** `#[frb(sync)]`: this writes a whole document to disk
  /// and fsyncs it, so it must not run on Dart's UI isolate. Budget S5
  /// (docs/13 §2.1) asks for a stress-document save to be non-blocking, and an
  /// async frb call is that for free.
  ///
  /// Media paths are rebased against the destination directory before writing
  /// (K-173), so a project saved somewhere new keeps relative links that work.
  /// A successful save clears the crash journal: the journal covers work
  /// *between* saves, so once the document is on disk it is redundant.
  Future<String> save({required String path}) => BridgeLib.instance.api
      .crateApiProjectProjectReferenceSave(that: this, path: path);

  /// Give this project its own cache location, or clear it so the project
  /// follows the application-wide choice again (`location: None`).
  ///
  /// An ordinary op, so it is undoable, journalled, and saved inside the `.lum`
  /// — which is the point of it being in the document at all: the choice travels
  /// with a copy of the project and survives being opened on another machine.
  /// Nothing already cached is moved or deleted; the frames in the old folder
  /// simply stop being addressed, and that folder may be deleted by hand at any
  /// time.
  void setCacheLocation({BridgeProjectCacheLocation? location}) =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceSetCacheLocation(
          that: this, location: location);

  Stream<WorkerResponse> startWorker() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceStartWorker(
        that: this,
      );

  void undo() => BridgeLib.instance.api.crateApiProjectProjectReferenceUndo(
        that: this,
      );

  @override
  int get hashCode => internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectReference &&
          runtimeType == other.runtimeType &&
          internalid == other.internalid;
}
