// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'project_item.dart';
import 'solid.dart';
import 'state.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`, `state`

class ProjectReference {
  final UuidValue internalid;

  const ProjectReference({
    required this.internalid,
  });

  List<ItemReference> getItems() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceGetItems(
        that: this,
      );

  void redo() => BridgeLib.instance.api.crateApiProjectProjectReferenceRedo(
        that: this,
      );

  Stream<WorkerResponse> startWorker() =>
      BridgeLib.instance.api.crateApiProjectProjectReferenceStartWorker(
        that: this,
      );

  void undo() => BridgeLib.instance.api.crateApiProjectProjectReferenceUndo(
        that: this,
      );

  @override
  int get hashCode => internalid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectReference &&
          runtimeType == other.runtimeType &&
          internalid == other.internalid;
}
