// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'solid.dart';
part 'project_item.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `item`, `project`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LumitProjectItemInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `eq`, `fmt`

@freezed
sealed class ItemReference with _$ItemReference {
  const ItemReference._();

  const factory ItemReference.footage(
    FootageReference field0,
  ) = ItemReference_Footage;
  const factory ItemReference.solid(
    SolidReference field0,
  ) = ItemReference_Solid;
  const factory ItemReference.composition(
    CompositionReference field0,
  ) = ItemReference_Composition;
  const factory ItemReference.folder(
    FolderReference field0,
  ) = ItemReference_Folder;

  bool equals({required ItemReference item}) => BridgeLib.instance.api
      .crateApiProjectItemItemReferenceEquals(that: this, item: item);

  String name() => BridgeLib.instance.api.crateApiProjectItemItemReferenceName(
        that: this,
      );
}
