// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// How a source frame is chosen when the map lands between two (docs/04 §10).
enum BridgeRetimeInterp {
  /// Round to the nearest source frame — crisp and deterministic.
  nearest,

  /// Crossfade the two neighbours.
  blend,

  /// Optical-flow synthesis. The flow engine is future work; the policy
  /// round-trips today so a project set to it is not silently downgraded.
  flow,
  ;
}
