// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'project.dart';
import 'project_item.dart';
import 'solid.dart';

// These functions are ignored because they are not marked as `pub`: `handle_change_callback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitBridgeState>>
abstract class LumitBridgeState implements RustOpaqueInterface {
  static ProjectReference? getCurrentProject() =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateGetCurrentProject();

  static ProjectReference newProject(
          {RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateNewProject(
          onChangeStream: onChangeStream);

  static ProjectReference? openProject(
          {required String path,
          RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateOpenProject(
          path: path, onChangeStream: onChangeStream);
}

class ScopedChange {
  final ProjectReference project;
  final ItemReference? item;
  final LayerReference? layer;

  const ScopedChange({
    required this.project,
    this.item,
    this.layer,
  });

  @override
  int get hashCode => project.hashCode ^ item.hashCode ^ layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScopedChange &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          item == other.item &&
          layer == other.layer;
}
