// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'composition.dart';
import 'folder.dart';
import 'footage.dart';
import 'layer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'project.dart';
import 'project_item.dart';
import 'solid.dart';
part 'state.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `handle_change_callback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitBridgeState>>
abstract class LumitBridgeState implements RustOpaqueInterface {
  static ProjectReference? getCurrentProject() =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateGetCurrentProject();

  static ProjectReference newProject(
          {RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateNewProject(
          onChangeStream: onChangeStream);

  static ProjectReference? openProject(
          {required String path,
          RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiStateLumitBridgeStateOpenProject(
          path: path, onChangeStream: onChangeStream);
}

/// A Viewer frame that came back as pixels rather than a GPU handle — the
/// portable path, used on any build without one of the zero-copy features (the
/// default on Windows). Dart turns `rgba` into a `ui.Image`.
///
/// Costly by construction: flutter_rust_bridge's SSE codec serialises a
/// `Vec<u8>` one byte at a time, measured at 8.8 ms for a 1080p frame and 37 ms
/// at 4K — the whole of budget B1 (docs/13 §2) for the 1080p case, before any
/// rendering. Prefer a zero-copy build where the platform allows one; see
/// docs/TODO.md for the fix.
class BridgeRenderedFrame {
  final int width;
  final int height;

  /// Tightly packed, straight (non-premultiplied) RGBA8: `width * height * 4`.
  final Uint8List rgba;

  const BridgeRenderedFrame({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRenderedFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// The Windows zero-copy Viewer frame (K-177): an NT handle to a shared D3D12
/// texture the Flutter runner imports directly, so no pixels cross the FFI
/// boundary. The handle is stable for the session and changes only when the
/// comp's dimensions do. The format is always RGBA8, so it is not carried.
class BridgeSharedFrameInfo {
  /// The NT `HANDLE` value. `u64` because a Windows handle is 64-bit; it
  /// reaches Dart as a `BigInt`.
  final BigInt handle;
  final int width;
  final int height;

  const BridgeSharedFrameInfo({
    required this.handle,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => handle.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSharedFrameInfo &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          width == other.width &&
          height == other.height;
}

class BridgeSharedFrameInfoLinux {
  final int fd;
  final int width;
  final int height;
  final int stride;
  final int offset;

  /// The DRM fourcc (`DRM_FORMAT_ABGR8888`, memory order R,G,B,A).
  final int drmFourcc;

  /// The DRM modifier (`DRM_FORMAT_MOD_LINEAR` = 0 on the linear-tiling path).
  final BigInt modifier;

  const BridgeSharedFrameInfoLinux({
    required this.fd,
    required this.width,
    required this.height,
    required this.stride,
    required this.offset,
    required this.drmFourcc,
    required this.modifier,
  });

  @override
  int get hashCode =>
      fd.hashCode ^
      width.hashCode ^
      height.hashCode ^
      stride.hashCode ^
      offset.hashCode ^
      drmFourcc.hashCode ^
      modifier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSharedFrameInfoLinux &&
          runtimeType == other.runtimeType &&
          fd == other.fd &&
          width == other.width &&
          height == other.height &&
          stride == other.stride &&
          offset == other.offset &&
          drmFourcc == other.drmFourcc &&
          modifier == other.modifier;
}

class ScopedChange {
  final ProjectReference project;
  final ItemReference? item;
  final LayerReference? layer;

  const ScopedChange({
    required this.project,
    this.item,
    this.layer,
  });

  @override
  int get hashCode => project.hashCode ^ item.hashCode ^ layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScopedChange &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          item == other.item &&
          layer == other.layer;
}

@freezed
sealed class WorkerResponse with _$WorkerResponse {
  const WorkerResponse._();

  /// Linux, `shared-texture-linux`.
  const factory WorkerResponse.renderedDmaBuf(
    BridgeSharedFrameInfoLinux field0,
  ) = WorkerResponse_RenderedDMABuf;

  /// Windows, `shared-texture`.
  const factory WorkerResponse.renderedSharedTexture(
    BridgeSharedFrameInfo field0,
  ) = WorkerResponse_RenderedSharedTexture;

  /// Everything else: a CPU read-back.
  const factory WorkerResponse.renderedPixels(
    BridgeRenderedFrame field0,
  ) = WorkerResponse_RenderedPixels;
}
