// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The machine's installed memory in bytes, or 0 where it cannot be asked.
BigInt systemMemoryBytes() =>
    BridgeLib.instance.api.crateApiSystemSystemMemoryBytes();

/// The primary adapter's dedicated video memory in bytes, or 0 where it
/// cannot be asked.
///
/// The *first* adapter DXGI enumerates, which is the one the renderer takes
/// too. A machine with a discrete card behind an integrated one would report
/// the integrated adapter's memory; that is a smaller ceiling than the truth,
/// which errs the safe way for a budget.
BigInt videoMemoryBytes() =>
    BridgeLib.instance.api.crateApiSystemVideoMemoryBytes();

/// Remember where the pointer is, and say whether it could be — a platform
/// with no implementation answers `false`, and the frontend then simply lets
/// the pointer travel as it always did.
bool freezeCursor() => BridgeLib.instance.api.crateApiSystemFreezeCursor();

/// Put the pointer back where [freeze_cursor] left it. Nothing at all when
/// nothing is frozen, so an extra call is harmless.
void restoreFrozenCursor() =>
    BridgeLib.instance.api.crateApiSystemRestoreFrozenCursor();

/// Let the pointer go again, at the end of the drag.
void thawCursor() => BridgeLib.instance.api.crateApiSystemThawCursor();
