// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The machine's installed memory in bytes, or 0 where it cannot be asked.
BigInt systemMemoryBytes() =>
    BridgeLib.instance.api.crateApiSystemSystemMemoryBytes();

/// The primary adapter's dedicated video memory in bytes, or 0 where it
/// cannot be asked.
///
/// The *first* adapter DXGI enumerates, which is the one the renderer takes
/// too. A machine with a discrete card behind an integrated one would report
/// the integrated adapter's memory; that is a smaller ceiling than the truth,
/// which errs the safe way for a budget.
BigInt videoMemoryBytes() =>
    BridgeLib.instance.api.crateApiSystemVideoMemoryBytes();
