// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/composition.dart';
import 'api/effect.dart';
import 'api/folder.dart';
import 'api/footage.dart';
import 'api/layer.dart';
import 'api/project.dart';
import 'api/project_item.dart';
import 'api/solid.dart';
import 'api/state.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class BridgeLibApiImplPlatform extends BaseApiImpl<BridgeLibWire> {
  BridgeLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BridgeEffectInstancePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BridgeErrorPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_EffectInstancePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LumitBridgeStatePtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          dynamic raw);

  @protected
  EffectInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          dynamic raw);

  @protected
  LumitBridgeState
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeEffectInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  BridgeError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          dynamic raw);

  @protected
  EffectInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          dynamic raw);

  @protected
  LumitBridgeState
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          dynamic raw);

  @protected
  RustStreamSink<ScopedChange> dco_decode_StreamSink_scoped_change_Sse(
      dynamic raw);

  @protected
  RustStreamSink<WorkerResponse> dco_decode_StreamSink_worker_response_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeBezierSide dco_decode_box_autoadd_bridge_bezier_side(dynamic raw);

  @protected
  BridgeColour dco_decode_box_autoadd_bridge_colour(dynamic raw);

  @protected
  BridgeCompSettings dco_decode_box_autoadd_bridge_comp_settings(dynamic raw);

  @protected
  BridgeEffectValue dco_decode_box_autoadd_bridge_effect_value(dynamic raw);

  @protected
  BridgeFileParam dco_decode_box_autoadd_bridge_file_param(dynamic raw);

  @protected
  BridgeMatte dco_decode_box_autoadd_bridge_matte(dynamic raw);

  @protected
  BridgePoint dco_decode_box_autoadd_bridge_point(dynamic raw);

  @protected
  BridgeRational dco_decode_box_autoadd_bridge_rational(dynamic raw);

  @protected
  BridgeRenderedFrame dco_decode_box_autoadd_bridge_rendered_frame(dynamic raw);

  @protected
  BridgeScalar dco_decode_box_autoadd_bridge_scalar(dynamic raw);

  @protected
  BridgeSharedFrameInfo dco_decode_box_autoadd_bridge_shared_frame_info(
      dynamic raw);

  @protected
  BridgeSharedFrameInfoLinux
      dco_decode_box_autoadd_bridge_shared_frame_info_linux(dynamic raw);

  @protected
  BridgeSpan dco_decode_box_autoadd_bridge_span(dynamic raw);

  @protected
  BridgeTransform dco_decode_box_autoadd_bridge_transform(dynamic raw);

  @protected
  CompositionReference dco_decode_box_autoadd_composition_reference(
      dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FolderReference dco_decode_box_autoadd_folder_reference(dynamic raw);

  @protected
  FootageReference dco_decode_box_autoadd_footage_reference(dynamic raw);

  @protected
  ItemReference dco_decode_box_autoadd_item_reference(dynamic raw);

  @protected
  LayerReference dco_decode_box_autoadd_layer_reference(dynamic raw);

  @protected
  ProjectReference dco_decode_box_autoadd_project_reference(dynamic raw);

  @protected
  SolidReference dco_decode_box_autoadd_solid_reference(dynamic raw);

  @protected
  BridgeBezierSide dco_decode_bridge_bezier_side(dynamic raw);

  @protected
  BridgeColour dco_decode_bridge_colour(dynamic raw);

  @protected
  BridgeCompSettings dco_decode_bridge_comp_settings(dynamic raw);

  @protected
  BridgeCompSize dco_decode_bridge_comp_size(dynamic raw);

  @protected
  BridgeEffectInfo dco_decode_bridge_effect_info(dynamic raw);

  @protected
  BridgeEffectValue dco_decode_bridge_effect_value(dynamic raw);

  @protected
  BridgeFileParam dco_decode_bridge_file_param(dynamic raw);

  @protected
  BridgeHistory dco_decode_bridge_history(dynamic raw);

  @protected
  BridgeKeyframe dco_decode_bridge_keyframe(dynamic raw);

  @protected
  BridgeLayerKind dco_decode_bridge_layer_kind(dynamic raw);

  @protected
  BridgeLayerSwitch dco_decode_bridge_layer_switch(dynamic raw);

  @protected
  BridgeLayerSwitches dco_decode_bridge_layer_switches(dynamic raw);

  @protected
  BridgeMarker dco_decode_bridge_marker(dynamic raw);

  @protected
  BridgeMatte dco_decode_bridge_matte(dynamic raw);

  @protected
  BridgeParamInfo dco_decode_bridge_param_info(dynamic raw);

  @protected
  BridgeParamKind dco_decode_bridge_param_kind(dynamic raw);

  @protected
  BridgePoint dco_decode_bridge_point(dynamic raw);

  @protected
  BridgeRational dco_decode_bridge_rational(dynamic raw);

  @protected
  BridgeRenderedFrame dco_decode_bridge_rendered_frame(dynamic raw);

  @protected
  BridgeScalar dco_decode_bridge_scalar(dynamic raw);

  @protected
  BridgeSharedFrameInfo dco_decode_bridge_shared_frame_info(dynamic raw);

  @protected
  BridgeSharedFrameInfoLinux dco_decode_bridge_shared_frame_info_linux(
      dynamic raw);

  @protected
  BridgeSideInterp dco_decode_bridge_side_interp(dynamic raw);

  @protected
  BridgeSpan dco_decode_bridge_span(dynamic raw);

  @protected
  BridgeTransform dco_decode_bridge_transform(dynamic raw);

  @protected
  BridgeTransformProp dco_decode_bridge_transform_prop(dynamic raw);

  @protected
  CompositionReference dco_decode_composition_reference(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FolderReference dco_decode_folder_reference(dynamic raw);

  @protected
  FootageReference dco_decode_footage_reference(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ItemReference dco_decode_item_reference(dynamic raw);

  @protected
  LayerReference dco_decode_layer_reference(dynamic raw);

  @protected
  List<BridgeEffectInstance>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeEffectInfo> dco_decode_list_bridge_effect_info(dynamic raw);

  @protected
  List<BridgeKeyframe> dco_decode_list_bridge_keyframe(dynamic raw);

  @protected
  List<BridgeMarker> dco_decode_list_bridge_marker(dynamic raw);

  @protected
  List<BridgeParamInfo> dco_decode_list_bridge_param_info(dynamic raw);

  @protected
  List<ItemReference> dco_decode_list_item_reference(dynamic raw);

  @protected
  List<LayerReference> dco_decode_list_layer_reference(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LumitMediaStatus dco_decode_lumit_media_status(dynamic raw);

  @protected
  RustStreamSink<ScopedChange>? dco_decode_opt_StreamSink_scoped_change_Sse(
      dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  UuidValue? dco_decode_opt_Uuid(dynamic raw);

  @protected
  BridgeMatte? dco_decode_opt_box_autoadd_bridge_matte(dynamic raw);

  @protected
  BridgeRenderedFrame? dco_decode_opt_box_autoadd_bridge_rendered_frame(
      dynamic raw);

  @protected
  BridgeSpan? dco_decode_opt_box_autoadd_bridge_span(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  ItemReference? dco_decode_opt_box_autoadd_item_reference(dynamic raw);

  @protected
  LayerReference? dco_decode_opt_box_autoadd_layer_reference(dynamic raw);

  @protected
  ProjectReference? dco_decode_opt_box_autoadd_project_reference(dynamic raw);

  @protected
  ProjectReference dco_decode_project_reference(dynamic raw);

  @protected
  ScopedChange dco_decode_scoped_change(dynamic raw);

  @protected
  SolidReference dco_decode_solid_reference(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorkerResponse dco_decode_worker_response(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          SseDeserializer deserializer);

  @protected
  EffectInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          SseDeserializer deserializer);

  @protected
  LumitBridgeState
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeEffectInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  BridgeError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          SseDeserializer deserializer);

  @protected
  EffectInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          SseDeserializer deserializer);

  @protected
  LumitBridgeState
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<ScopedChange> sse_decode_StreamSink_scoped_change_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<WorkerResponse> sse_decode_StreamSink_worker_response_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeBezierSide sse_decode_box_autoadd_bridge_bezier_side(
      SseDeserializer deserializer);

  @protected
  BridgeColour sse_decode_box_autoadd_bridge_colour(
      SseDeserializer deserializer);

  @protected
  BridgeCompSettings sse_decode_box_autoadd_bridge_comp_settings(
      SseDeserializer deserializer);

  @protected
  BridgeEffectValue sse_decode_box_autoadd_bridge_effect_value(
      SseDeserializer deserializer);

  @protected
  BridgeFileParam sse_decode_box_autoadd_bridge_file_param(
      SseDeserializer deserializer);

  @protected
  BridgeMatte sse_decode_box_autoadd_bridge_matte(SseDeserializer deserializer);

  @protected
  BridgePoint sse_decode_box_autoadd_bridge_point(SseDeserializer deserializer);

  @protected
  BridgeRational sse_decode_box_autoadd_bridge_rational(
      SseDeserializer deserializer);

  @protected
  BridgeRenderedFrame sse_decode_box_autoadd_bridge_rendered_frame(
      SseDeserializer deserializer);

  @protected
  BridgeScalar sse_decode_box_autoadd_bridge_scalar(
      SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfo sse_decode_box_autoadd_bridge_shared_frame_info(
      SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfoLinux
      sse_decode_box_autoadd_bridge_shared_frame_info_linux(
          SseDeserializer deserializer);

  @protected
  BridgeSpan sse_decode_box_autoadd_bridge_span(SseDeserializer deserializer);

  @protected
  BridgeTransform sse_decode_box_autoadd_bridge_transform(
      SseDeserializer deserializer);

  @protected
  CompositionReference sse_decode_box_autoadd_composition_reference(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FolderReference sse_decode_box_autoadd_folder_reference(
      SseDeserializer deserializer);

  @protected
  FootageReference sse_decode_box_autoadd_footage_reference(
      SseDeserializer deserializer);

  @protected
  ItemReference sse_decode_box_autoadd_item_reference(
      SseDeserializer deserializer);

  @protected
  LayerReference sse_decode_box_autoadd_layer_reference(
      SseDeserializer deserializer);

  @protected
  ProjectReference sse_decode_box_autoadd_project_reference(
      SseDeserializer deserializer);

  @protected
  SolidReference sse_decode_box_autoadd_solid_reference(
      SseDeserializer deserializer);

  @protected
  BridgeBezierSide sse_decode_bridge_bezier_side(SseDeserializer deserializer);

  @protected
  BridgeColour sse_decode_bridge_colour(SseDeserializer deserializer);

  @protected
  BridgeCompSettings sse_decode_bridge_comp_settings(
      SseDeserializer deserializer);

  @protected
  BridgeCompSize sse_decode_bridge_comp_size(SseDeserializer deserializer);

  @protected
  BridgeEffectInfo sse_decode_bridge_effect_info(SseDeserializer deserializer);

  @protected
  BridgeEffectValue sse_decode_bridge_effect_value(
      SseDeserializer deserializer);

  @protected
  BridgeFileParam sse_decode_bridge_file_param(SseDeserializer deserializer);

  @protected
  BridgeHistory sse_decode_bridge_history(SseDeserializer deserializer);

  @protected
  BridgeKeyframe sse_decode_bridge_keyframe(SseDeserializer deserializer);

  @protected
  BridgeLayerKind sse_decode_bridge_layer_kind(SseDeserializer deserializer);

  @protected
  BridgeLayerSwitch sse_decode_bridge_layer_switch(
      SseDeserializer deserializer);

  @protected
  BridgeLayerSwitches sse_decode_bridge_layer_switches(
      SseDeserializer deserializer);

  @protected
  BridgeMarker sse_decode_bridge_marker(SseDeserializer deserializer);

  @protected
  BridgeMatte sse_decode_bridge_matte(SseDeserializer deserializer);

  @protected
  BridgeParamInfo sse_decode_bridge_param_info(SseDeserializer deserializer);

  @protected
  BridgeParamKind sse_decode_bridge_param_kind(SseDeserializer deserializer);

  @protected
  BridgePoint sse_decode_bridge_point(SseDeserializer deserializer);

  @protected
  BridgeRational sse_decode_bridge_rational(SseDeserializer deserializer);

  @protected
  BridgeRenderedFrame sse_decode_bridge_rendered_frame(
      SseDeserializer deserializer);

  @protected
  BridgeScalar sse_decode_bridge_scalar(SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfo sse_decode_bridge_shared_frame_info(
      SseDeserializer deserializer);

  @protected
  BridgeSharedFrameInfoLinux sse_decode_bridge_shared_frame_info_linux(
      SseDeserializer deserializer);

  @protected
  BridgeSideInterp sse_decode_bridge_side_interp(SseDeserializer deserializer);

  @protected
  BridgeSpan sse_decode_bridge_span(SseDeserializer deserializer);

  @protected
  BridgeTransform sse_decode_bridge_transform(SseDeserializer deserializer);

  @protected
  BridgeTransformProp sse_decode_bridge_transform_prop(
      SseDeserializer deserializer);

  @protected
  CompositionReference sse_decode_composition_reference(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FolderReference sse_decode_folder_reference(SseDeserializer deserializer);

  @protected
  FootageReference sse_decode_footage_reference(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ItemReference sse_decode_item_reference(SseDeserializer deserializer);

  @protected
  LayerReference sse_decode_layer_reference(SseDeserializer deserializer);

  @protected
  List<BridgeEffectInstance>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeEffectInfo> sse_decode_list_bridge_effect_info(
      SseDeserializer deserializer);

  @protected
  List<BridgeKeyframe> sse_decode_list_bridge_keyframe(
      SseDeserializer deserializer);

  @protected
  List<BridgeMarker> sse_decode_list_bridge_marker(
      SseDeserializer deserializer);

  @protected
  List<BridgeParamInfo> sse_decode_list_bridge_param_info(
      SseDeserializer deserializer);

  @protected
  List<ItemReference> sse_decode_list_item_reference(
      SseDeserializer deserializer);

  @protected
  List<LayerReference> sse_decode_list_layer_reference(
      SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LumitMediaStatus sse_decode_lumit_media_status(SseDeserializer deserializer);

  @protected
  RustStreamSink<ScopedChange>? sse_decode_opt_StreamSink_scoped_change_Sse(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  UuidValue? sse_decode_opt_Uuid(SseDeserializer deserializer);

  @protected
  BridgeMatte? sse_decode_opt_box_autoadd_bridge_matte(
      SseDeserializer deserializer);

  @protected
  BridgeRenderedFrame? sse_decode_opt_box_autoadd_bridge_rendered_frame(
      SseDeserializer deserializer);

  @protected
  BridgeSpan? sse_decode_opt_box_autoadd_bridge_span(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ItemReference? sse_decode_opt_box_autoadd_item_reference(
      SseDeserializer deserializer);

  @protected
  LayerReference? sse_decode_opt_box_autoadd_layer_reference(
      SseDeserializer deserializer);

  @protected
  ProjectReference? sse_decode_opt_box_autoadd_project_reference(
      SseDeserializer deserializer);

  @protected
  ProjectReference sse_decode_project_reference(SseDeserializer deserializer);

  @protected
  ScopedChange sse_decode_scoped_change(SseDeserializer deserializer);

  @protected
  SolidReference sse_decode_solid_reference(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorkerResponse sse_decode_worker_response(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          BridgeError self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          EffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          LumitBridgeState self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          BridgeError self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          EffectInstance self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          LumitBridgeState self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_scoped_change_Sse(
      RustStreamSink<ScopedChange> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_worker_response_Sse(
      RustStreamSink<WorkerResponse> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_bezier_side(
      BridgeBezierSide self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_colour(
      BridgeColour self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_comp_settings(
      BridgeCompSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_effect_value(
      BridgeEffectValue self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_file_param(
      BridgeFileParam self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_matte(
      BridgeMatte self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_point(
      BridgePoint self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_rational(
      BridgeRational self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_rendered_frame(
      BridgeRenderedFrame self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_scalar(
      BridgeScalar self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_shared_frame_info(
      BridgeSharedFrameInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_shared_frame_info_linux(
      BridgeSharedFrameInfoLinux self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_span(
      BridgeSpan self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_transform(
      BridgeTransform self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_composition_reference(
      CompositionReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_folder_reference(
      FolderReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_footage_reference(
      FootageReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_item_reference(
      ItemReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_layer_reference(
      LayerReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_project_reference(
      ProjectReference self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_solid_reference(
      SolidReference self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_bezier_side(
      BridgeBezierSide self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_colour(BridgeColour self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_comp_settings(
      BridgeCompSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_comp_size(
      BridgeCompSize self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_effect_info(
      BridgeEffectInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_effect_value(
      BridgeEffectValue self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_file_param(
      BridgeFileParam self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_history(BridgeHistory self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_keyframe(
      BridgeKeyframe self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_kind(
      BridgeLayerKind self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_switch(
      BridgeLayerSwitch self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_layer_switches(
      BridgeLayerSwitches self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_marker(BridgeMarker self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_matte(BridgeMatte self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_info(
      BridgeParamInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_param_kind(
      BridgeParamKind self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_point(BridgePoint self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_rational(
      BridgeRational self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_rendered_frame(
      BridgeRenderedFrame self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_scalar(BridgeScalar self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_shared_frame_info(
      BridgeSharedFrameInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_shared_frame_info_linux(
      BridgeSharedFrameInfoLinux self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_side_interp(
      BridgeSideInterp self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_span(BridgeSpan self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_transform(
      BridgeTransform self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_transform_prop(
      BridgeTransformProp self, SseSerializer serializer);

  @protected
  void sse_encode_composition_reference(
      CompositionReference self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_folder_reference(
      FolderReference self, SseSerializer serializer);

  @protected
  void sse_encode_footage_reference(
      FootageReference self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_item_reference(ItemReference self, SseSerializer serializer);

  @protected
  void sse_encode_layer_reference(
      LayerReference self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          List<BridgeEffectInstance> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_effect_info(
      List<BridgeEffectInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_keyframe(
      List<BridgeKeyframe> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_marker(
      List<BridgeMarker> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_param_info(
      List<BridgeParamInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_item_reference(
      List<ItemReference> self, SseSerializer serializer);

  @protected
  void sse_encode_list_layer_reference(
      List<LayerReference> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_lumit_media_status(
      LumitMediaStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_StreamSink_scoped_change_Sse(
      RustStreamSink<ScopedChange>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Uuid(UuidValue? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_matte(
      BridgeMatte? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_rendered_frame(
      BridgeRenderedFrame? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_span(
      BridgeSpan? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_item_reference(
      ItemReference? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_layer_reference(
      LayerReference? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_project_reference(
      ProjectReference? self, SseSerializer serializer);

  @protected
  void sse_encode_project_reference(
      ProjectReference self, SseSerializer serializer);

  @protected
  void sse_encode_scoped_change(ScopedChange self, SseSerializer serializer);

  @protected
  void sse_encode_solid_reference(
      SolidReference self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_worker_response(
      WorkerResponse self, SseSerializer serializer);
}

// Section: wire_class

class BridgeLibWire implements BaseWire {
  BridgeLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
              ptr);
}

@JS('wasm_bindgen')
external BridgeLibWasmModule get wasmModule;

@JS()
@anonymous
extension type BridgeLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          int ptr);
}
