// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/composition.dart';
import 'api/effect.dart';
import 'api/folder.dart';
import 'api/footage.dart';
import 'api/layer.dart';
import 'api/project.dart';
import 'api/project_item.dart';
import 'api/solid.dart';
import 'api/state.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// Main entrypoint of the Rust API
class BridgeLib
    extends BaseEntrypoint<BridgeLibApi, BridgeLibApiImpl, BridgeLibWire> {
  @internal
  static final instance = BridgeLib._();

  BridgeLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    BridgeLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required BridgeLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<BridgeLibApiImpl, BridgeLibWire> get apiImplConstructor =>
      BridgeLibApiImpl.new;

  @override
  WireConstructor<BridgeLibWire> get wireConstructor =>
      BridgeLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2021470981;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'lumit_bridge',
    ioDirectory: '../crates/lumit-bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class BridgeLibApi extends BaseApi {
  List<String> crateApiEffectBridgeEffectInstanceGetParameters(
      {required BridgeEffectInstance that});

  double? crateApiEffectBridgeEffectInstanceGetValue(
      {required BridgeEffectInstance that, required String id});

  String crateApiEffectBridgeEffectInstanceName(
      {required BridgeEffectInstance that});

  Future<BridgeEffectInstance> crateApiEffectBridgeEffectInstanceNew(
      {required EffectInstance effect});

  String crateApiEffectBridgeEffectInstanceSerialize(
      {required BridgeEffectInstance that});

  void crateApiEffectBridgeEffectInstanceSetValue(
      {required BridgeEffectInstance that,
      required String id,
      required double value});

  ProjectReference? crateApiStateLumitBridgeStateGetCurrentProject();

  ProjectReference crateApiStateLumitBridgeStateNewProject(
      {RustStreamSink<ScopedChange>? onChangeStream});

  ProjectReference? crateApiStateLumitBridgeStateOpenProject(
      {required String path, RustStreamSink<ScopedChange>? onChangeStream});

  List<LayerReference> crateApiCompositionCompositionReferenceGetLayers(
      {required CompositionReference that});

  void crateApiCompositionCompositionReferenceRenderFrame(
      {required CompositionReference that, required BigInt frame});

  void crateApiCompositionCompositionReferenceRenderFrameWithPreview(
      {required CompositionReference that,
      required BigInt frame,
      required LayerReference layer,
      required List<BridgeEffectInstance> effects});

  Future<LumitMediaStatus> crateApiFootageFootageReferenceGetStatus(
      {required FootageReference that});

  bool crateApiProjectItemItemReferenceEquals(
      {required ItemReference that, required ItemReference item});

  String crateApiProjectItemItemReferenceName({required ItemReference that});

  bool crateApiLayerLayerReferenceEquals(
      {required LayerReference that, required LayerReference layer});

  List<BridgeEffectInstance> crateApiLayerLayerReferenceGetEffects(
      {required LayerReference that});

  String crateApiLayerLayerReferenceGetName({required LayerReference that});

  void crateApiLayerLayerReferenceRename(
      {required LayerReference that, required String name});

  List<ItemReference> crateApiProjectProjectReferenceGetItems(
      {required ProjectReference that});

  void crateApiProjectProjectReferenceRedo({required ProjectReference that});

  Stream<WorkerResponse> crateApiProjectProjectReferenceStartWorker(
      {required ProjectReference that});

  void crateApiProjectProjectReferenceUndo({required ProjectReference that});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_BridgeEffectInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_BridgeEffectInstance;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BridgeEffectInstancePtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_BridgeError;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_BridgeError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BridgeErrorPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EffectInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EffectInstance;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_EffectInstancePtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LumitBridgeState;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LumitBridgeState;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_LumitBridgeStatePtr;
}

class BridgeLibApiImpl extends BridgeLibApiImplPlatform
    implements BridgeLibApi {
  BridgeLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<String> crateApiEffectBridgeEffectInstanceGetParameters(
      {required BridgeEffectInstance that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEffectBridgeEffectInstanceGetParametersConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEffectBridgeEffectInstanceGetParametersConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeEffectInstance_get_parameters",
        argNames: ["that"],
      );

  @override
  double? crateApiEffectBridgeEffectInstanceGetValue(
      {required BridgeEffectInstance that, required String id}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
            that, serializer);
        sse_encode_String(id, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_f_64,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiEffectBridgeEffectInstanceGetValueConstMeta,
      argValues: [that, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEffectBridgeEffectInstanceGetValueConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeEffectInstance_get_value",
        argNames: ["that", "id"],
      );

  @override
  String crateApiEffectBridgeEffectInstanceName(
      {required BridgeEffectInstance that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEffectBridgeEffectInstanceNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEffectBridgeEffectInstanceNameConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeEffectInstance_name",
        argNames: ["that"],
      );

  @override
  Future<BridgeEffectInstance> crateApiEffectBridgeEffectInstanceNew(
      {required EffectInstance effect}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
            effect, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEffectBridgeEffectInstanceNewConstMeta,
      argValues: [effect],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEffectBridgeEffectInstanceNewConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeEffectInstance_new",
        argNames: ["effect"],
      );

  @override
  String crateApiEffectBridgeEffectInstanceSerialize(
      {required BridgeEffectInstance that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEffectBridgeEffectInstanceSerializeConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEffectBridgeEffectInstanceSerializeConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeEffectInstance_serialize",
        argNames: ["that"],
      );

  @override
  void crateApiEffectBridgeEffectInstanceSetValue(
      {required BridgeEffectInstance that,
      required String id,
      required double value}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
            that, serializer);
        sse_encode_String(id, serializer);
        sse_encode_f_64(value, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiEffectBridgeEffectInstanceSetValueConstMeta,
      argValues: [that, id, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEffectBridgeEffectInstanceSetValueConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeEffectInstance_set_value",
        argNames: ["that", "id", "value"],
      );

  @override
  ProjectReference? crateApiStateLumitBridgeStateGetCurrentProject() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_project_reference,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiStateLumitBridgeStateGetCurrentProjectConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStateLumitBridgeStateGetCurrentProjectConstMeta =>
      const TaskConstMeta(
        debugName: "LumitBridgeState_get_current_project",
        argNames: [],
      );

  @override
  ProjectReference crateApiStateLumitBridgeStateNewProject(
      {RustStreamSink<ScopedChange>? onChangeStream}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_StreamSink_scoped_change_Sse(onChangeStream, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_project_reference,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiStateLumitBridgeStateNewProjectConstMeta,
      argValues: [onChangeStream],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStateLumitBridgeStateNewProjectConstMeta =>
      const TaskConstMeta(
        debugName: "LumitBridgeState_new_project",
        argNames: ["onChangeStream"],
      );

  @override
  ProjectReference? crateApiStateLumitBridgeStateOpenProject(
      {required String path, RustStreamSink<ScopedChange>? onChangeStream}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_opt_StreamSink_scoped_change_Sse(onChangeStream, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_project_reference,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiStateLumitBridgeStateOpenProjectConstMeta,
      argValues: [path, onChangeStream],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStateLumitBridgeStateOpenProjectConstMeta =>
      const TaskConstMeta(
        debugName: "LumitBridgeState_open_project",
        argNames: ["path", "onChangeStream"],
      );

  @override
  List<LayerReference> crateApiCompositionCompositionReferenceGetLayers(
      {required CompositionReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_composition_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_layer_reference,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiCompositionCompositionReferenceGetLayersConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCompositionCompositionReferenceGetLayersConstMeta =>
          const TaskConstMeta(
            debugName: "composition_reference_get_layers",
            argNames: ["that"],
          );

  @override
  void crateApiCompositionCompositionReferenceRenderFrame(
      {required CompositionReference that, required BigInt frame}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_composition_reference(that, serializer);
        sse_encode_u_64(frame, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiCompositionCompositionReferenceRenderFrameConstMeta,
      argValues: [that, frame],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCompositionCompositionReferenceRenderFrameConstMeta =>
          const TaskConstMeta(
            debugName: "composition_reference_render_frame",
            argNames: ["that", "frame"],
          );

  @override
  void crateApiCompositionCompositionReferenceRenderFrameWithPreview(
      {required CompositionReference that,
      required BigInt frame,
      required LayerReference layer,
      required List<BridgeEffectInstance> effects}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_composition_reference(that, serializer);
        sse_encode_u_64(frame, serializer);
        sse_encode_box_autoadd_layer_reference(layer, serializer);
        sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
            effects, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta:
          kCrateApiCompositionCompositionReferenceRenderFrameWithPreviewConstMeta,
      argValues: [that, frame, layer, effects],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCompositionCompositionReferenceRenderFrameWithPreviewConstMeta =>
          const TaskConstMeta(
            debugName: "composition_reference_render_frame_with_preview",
            argNames: ["that", "frame", "layer", "effects"],
          );

  @override
  Future<LumitMediaStatus> crateApiFootageFootageReferenceGetStatus(
      {required FootageReference that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_footage_reference(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_lumit_media_status,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiFootageFootageReferenceGetStatusConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFootageFootageReferenceGetStatusConstMeta =>
      const TaskConstMeta(
        debugName: "footage_reference_get_status",
        argNames: ["that"],
      );

  @override
  bool crateApiProjectItemItemReferenceEquals(
      {required ItemReference that, required ItemReference item}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_item_reference(that, serializer);
        sse_encode_box_autoadd_item_reference(item, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiProjectItemItemReferenceEqualsConstMeta,
      argValues: [that, item],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProjectItemItemReferenceEqualsConstMeta =>
      const TaskConstMeta(
        debugName: "item_reference_equals",
        argNames: ["that", "item"],
      );

  @override
  String crateApiProjectItemItemReferenceName({required ItemReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_item_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiProjectItemItemReferenceNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProjectItemItemReferenceNameConstMeta =>
      const TaskConstMeta(
        debugName: "item_reference_name",
        argNames: ["that"],
      );

  @override
  bool crateApiLayerLayerReferenceEquals(
      {required LayerReference that, required LayerReference layer}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_layer_reference(that, serializer);
        sse_encode_box_autoadd_layer_reference(layer, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLayerLayerReferenceEqualsConstMeta,
      argValues: [that, layer],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLayerLayerReferenceEqualsConstMeta =>
      const TaskConstMeta(
        debugName: "layer_reference_equals",
        argNames: ["that", "layer"],
      );

  @override
  List<BridgeEffectInstance> crateApiLayerLayerReferenceGetEffects(
      {required LayerReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_layer_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiLayerLayerReferenceGetEffectsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLayerLayerReferenceGetEffectsConstMeta =>
      const TaskConstMeta(
        debugName: "layer_reference_get_effects",
        argNames: ["that"],
      );

  @override
  String crateApiLayerLayerReferenceGetName({required LayerReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_layer_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiLayerLayerReferenceGetNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLayerLayerReferenceGetNameConstMeta =>
      const TaskConstMeta(
        debugName: "layer_reference_get_name",
        argNames: ["that"],
      );

  @override
  void crateApiLayerLayerReferenceRename(
      {required LayerReference that, required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_layer_reference(that, serializer);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiLayerLayerReferenceRenameConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLayerLayerReferenceRenameConstMeta =>
      const TaskConstMeta(
        debugName: "layer_reference_rename",
        argNames: ["that", "name"],
      );

  @override
  List<ItemReference> crateApiProjectProjectReferenceGetItems(
      {required ProjectReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_item_reference,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiProjectProjectReferenceGetItemsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProjectProjectReferenceGetItemsConstMeta =>
      const TaskConstMeta(
        debugName: "project_reference_get_items",
        argNames: ["that"],
      );

  @override
  void crateApiProjectProjectReferenceRedo({required ProjectReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiProjectProjectReferenceRedoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProjectProjectReferenceRedoConstMeta =>
      const TaskConstMeta(
        debugName: "project_reference_redo",
        argNames: ["that"],
      );

  @override
  Stream<WorkerResponse> crateApiProjectProjectReferenceStartWorker(
      {required ProjectReference that}) {
    final onReponse = RustStreamSink<WorkerResponse>();
    handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project_reference(that, serializer);
        sse_encode_StreamSink_worker_response_Sse(onReponse, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiProjectProjectReferenceStartWorkerConstMeta,
      argValues: [that, onReponse],
      apiImpl: this,
    ));
    return onReponse.stream;
  }

  TaskConstMeta get kCrateApiProjectProjectReferenceStartWorkerConstMeta =>
      const TaskConstMeta(
        debugName: "project_reference_start_worker",
        argNames: ["that", "onReponse"],
      );

  @override
  void crateApiProjectProjectReferenceUndo({required ProjectReference that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_project_reference(that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError,
      ),
      constMeta: kCrateApiProjectProjectReferenceUndoConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProjectProjectReferenceUndoConstMeta =>
      const TaskConstMeta(
        debugName: "project_reference_undo",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_BridgeEffectInstance => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_BridgeEffectInstance => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_BridgeError => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_BridgeError => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_EffectInstance => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_EffectInstance => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_LumitBridgeState => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_LumitBridgeState => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  BridgeEffectInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EffectInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EffectInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LumitBridgeState
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LumitBridgeStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeEffectInstance
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeEffectInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeEffectInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  EffectInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EffectInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LumitBridgeState
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LumitBridgeStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<ScopedChange> dco_decode_StreamSink_scoped_change_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<WorkerResponse> dco_decode_StreamSink_worker_response_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  UuidValue dco_decode_Uuid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UuidValue.fromByteList(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeSharedFrameInfoLinux
      dco_decode_box_autoadd_bridge_shared_frame_info_linux(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_shared_frame_info_linux(raw);
  }

  @protected
  CompositionReference dco_decode_box_autoadd_composition_reference(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_composition_reference(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderReference dco_decode_box_autoadd_folder_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_folder_reference(raw);
  }

  @protected
  FootageReference dco_decode_box_autoadd_footage_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_footage_reference(raw);
  }

  @protected
  ItemReference dco_decode_box_autoadd_item_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_item_reference(raw);
  }

  @protected
  LayerReference dco_decode_box_autoadd_layer_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_layer_reference(raw);
  }

  @protected
  ProjectReference dco_decode_box_autoadd_project_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_project_reference(raw);
  }

  @protected
  SolidReference dco_decode_box_autoadd_solid_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_solid_reference(raw);
  }

  @protected
  BridgeSharedFrameInfoLinux dco_decode_bridge_shared_frame_info_linux(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeSharedFrameInfoLinux(
      fd: dco_decode_i_32(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      stride: dco_decode_u_32(arr[3]),
      offset: dco_decode_u_32(arr[4]),
      drmFourcc: dco_decode_u_32(arr[5]),
      modifier: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  CompositionReference dco_decode_composition_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CompositionReference(
      internalproject: dco_decode_Uuid(arr[0]),
      internalid: dco_decode_Uuid(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderReference dco_decode_folder_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FolderReference(
      internalproject: dco_decode_Uuid(arr[0]),
      internalid: dco_decode_Uuid(arr[1]),
    );
  }

  @protected
  FootageReference dco_decode_footage_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FootageReference(
      internalproject: dco_decode_Uuid(arr[0]),
      internalid: dco_decode_Uuid(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ItemReference dco_decode_item_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ItemReference_Footage(
          dco_decode_box_autoadd_footage_reference(raw[1]),
        );
      case 1:
        return ItemReference_Solid(
          dco_decode_box_autoadd_solid_reference(raw[1]),
        );
      case 2:
        return ItemReference_Composition(
          dco_decode_box_autoadd_composition_reference(raw[1]),
        );
      case 3:
        return ItemReference_Folder(
          dco_decode_box_autoadd_folder_reference(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  LayerReference dco_decode_layer_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LayerReference(
      internalprojectId: dco_decode_Uuid(arr[0]),
      internalcompId: dco_decode_Uuid(arr[1]),
      internallayerId: dco_decode_Uuid(arr[2]),
    );
  }

  @protected
  List<BridgeEffectInstance>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
            dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance)
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ItemReference> dco_decode_list_item_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_item_reference).toList();
  }

  @protected
  List<LayerReference> dco_decode_list_layer_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_layer_reference).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LumitMediaStatus dco_decode_lumit_media_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LumitMediaStatus.values[raw as int];
  }

  @protected
  RustStreamSink<ScopedChange>? dco_decode_opt_StreamSink_scoped_change_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_StreamSink_scoped_change_Sse(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  ItemReference? dco_decode_opt_box_autoadd_item_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_item_reference(raw);
  }

  @protected
  LayerReference? dco_decode_opt_box_autoadd_layer_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_layer_reference(raw);
  }

  @protected
  ProjectReference? dco_decode_opt_box_autoadd_project_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_project_reference(raw);
  }

  @protected
  ProjectReference dco_decode_project_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ProjectReference(
      internalid: dco_decode_Uuid(arr[0]),
    );
  }

  @protected
  ScopedChange dco_decode_scoped_change(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScopedChange(
      project: dco_decode_project_reference(arr[0]),
      item: dco_decode_opt_box_autoadd_item_reference(arr[1]),
      layer: dco_decode_opt_box_autoadd_layer_reference(arr[2]),
    );
  }

  @protected
  SolidReference dco_decode_solid_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SolidReference(
      internalproject: dco_decode_Uuid(arr[0]),
      internalid: dco_decode_Uuid(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WorkerResponse dco_decode_worker_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return WorkerResponse_RenderedDMABuf(
          dco_decode_box_autoadd_bridge_shared_frame_info_linux(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  BridgeEffectInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  BridgeError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeErrorImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EffectInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EffectInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LumitBridgeState
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LumitBridgeStateImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  BridgeEffectInstance
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  BridgeEffectInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  BridgeEffectInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeEffectInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  BridgeError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeErrorImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  EffectInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return EffectInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  LumitBridgeState
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LumitBridgeStateImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<ScopedChange> sse_decode_StreamSink_scoped_change_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<WorkerResponse> sse_decode_StreamSink_worker_response_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return UuidValue.fromByteList(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeSharedFrameInfoLinux
      sse_decode_box_autoadd_bridge_shared_frame_info_linux(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_shared_frame_info_linux(deserializer));
  }

  @protected
  CompositionReference sse_decode_box_autoadd_composition_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_composition_reference(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FolderReference sse_decode_box_autoadd_folder_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_folder_reference(deserializer));
  }

  @protected
  FootageReference sse_decode_box_autoadd_footage_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_footage_reference(deserializer));
  }

  @protected
  ItemReference sse_decode_box_autoadd_item_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_item_reference(deserializer));
  }

  @protected
  LayerReference sse_decode_box_autoadd_layer_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_layer_reference(deserializer));
  }

  @protected
  ProjectReference sse_decode_box_autoadd_project_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_project_reference(deserializer));
  }

  @protected
  SolidReference sse_decode_box_autoadd_solid_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_solid_reference(deserializer));
  }

  @protected
  BridgeSharedFrameInfoLinux sse_decode_bridge_shared_frame_info_linux(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fd = sse_decode_i_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_stride = sse_decode_u_32(deserializer);
    var var_offset = sse_decode_u_32(deserializer);
    var var_drmFourcc = sse_decode_u_32(deserializer);
    var var_modifier = sse_decode_u_64(deserializer);
    return BridgeSharedFrameInfoLinux(
        fd: var_fd,
        width: var_width,
        height: var_height,
        stride: var_stride,
        offset: var_offset,
        drmFourcc: var_drmFourcc,
        modifier: var_modifier);
  }

  @protected
  CompositionReference sse_decode_composition_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_internalproject = sse_decode_Uuid(deserializer);
    var var_internalid = sse_decode_Uuid(deserializer);
    return CompositionReference(
        internalproject: var_internalproject, internalid: var_internalid);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FolderReference sse_decode_folder_reference(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_internalproject = sse_decode_Uuid(deserializer);
    var var_internalid = sse_decode_Uuid(deserializer);
    return FolderReference(
        internalproject: var_internalproject, internalid: var_internalid);
  }

  @protected
  FootageReference sse_decode_footage_reference(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_internalproject = sse_decode_Uuid(deserializer);
    var var_internalid = sse_decode_Uuid(deserializer);
    return FootageReference(
        internalproject: var_internalproject, internalid: var_internalid);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ItemReference sse_decode_item_reference(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_footage_reference(deserializer);
        return ItemReference_Footage(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_solid_reference(deserializer);
        return ItemReference_Solid(var_field0);
      case 2:
        var var_field0 =
            sse_decode_box_autoadd_composition_reference(deserializer);
        return ItemReference_Composition(var_field0);
      case 3:
        var var_field0 = sse_decode_box_autoadd_folder_reference(deserializer);
        return ItemReference_Folder(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  LayerReference sse_decode_layer_reference(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_internalprojectId = sse_decode_Uuid(deserializer);
    var var_internalcompId = sse_decode_Uuid(deserializer);
    var var_internallayerId = sse_decode_Uuid(deserializer);
    return LayerReference(
        internalprojectId: var_internalprojectId,
        internalcompId: var_internalcompId,
        internallayerId: var_internallayerId);
  }

  @protected
  List<BridgeEffectInstance>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeEffectInstance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
          sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
              deserializer));
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ItemReference> sse_decode_list_item_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ItemReference>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_item_reference(deserializer));
    }
    return ans_;
  }

  @protected
  List<LayerReference> sse_decode_list_layer_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LayerReference>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_layer_reference(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LumitMediaStatus sse_decode_lumit_media_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LumitMediaStatus.values[inner];
  }

  @protected
  RustStreamSink<ScopedChange>? sse_decode_opt_StreamSink_scoped_change_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_StreamSink_scoped_change_Sse(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ItemReference? sse_decode_opt_box_autoadd_item_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_item_reference(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LayerReference? sse_decode_opt_box_autoadd_layer_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_layer_reference(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectReference? sse_decode_opt_box_autoadd_project_reference(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_project_reference(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectReference sse_decode_project_reference(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_internalid = sse_decode_Uuid(deserializer);
    return ProjectReference(internalid: var_internalid);
  }

  @protected
  ScopedChange sse_decode_scoped_change(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_project = sse_decode_project_reference(deserializer);
    var var_item = sse_decode_opt_box_autoadd_item_reference(deserializer);
    var var_layer = sse_decode_opt_box_autoadd_layer_reference(deserializer);
    return ScopedChange(project: var_project, item: var_item, layer: var_layer);
  }

  @protected
  SolidReference sse_decode_solid_reference(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_internalproject = sse_decode_Uuid(deserializer);
    var var_internalid = sse_decode_Uuid(deserializer);
    return SolidReference(
        internalproject: var_internalproject, internalid: var_internalid);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WorkerResponse sse_decode_worker_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 =
            sse_decode_box_autoadd_bridge_shared_frame_info_linux(deserializer);
        return WorkerResponse_RenderedDMABuf(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as BridgeEffectInstanceImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as BridgeErrorImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          EffectInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EffectInstanceImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          LumitBridgeState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LumitBridgeStateImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as BridgeEffectInstanceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as BridgeEffectInstanceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          BridgeEffectInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as BridgeEffectInstanceImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeError(
          BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as BridgeErrorImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEffectInstance(
          EffectInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as EffectInstanceImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLumitBridgeState(
          LumitBridgeState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as LumitBridgeStateImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_scoped_change_Sse(
      RustStreamSink<ScopedChange> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_scoped_change,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_worker_response_Sse(
      RustStreamSink<WorkerResponse> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_worker_response,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.toBytes(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_shared_frame_info_linux(
      BridgeSharedFrameInfoLinux self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_shared_frame_info_linux(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_composition_reference(
      CompositionReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_composition_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_folder_reference(
      FolderReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_folder_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_footage_reference(
      FootageReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_footage_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_item_reference(
      ItemReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_item_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_layer_reference(
      LayerReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_layer_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_project_reference(
      ProjectReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_solid_reference(
      SolidReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_solid_reference(self, serializer);
  }

  @protected
  void sse_encode_bridge_shared_frame_info_linux(
      BridgeSharedFrameInfoLinux self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.fd, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_32(self.stride, serializer);
    sse_encode_u_32(self.offset, serializer);
    sse_encode_u_32(self.drmFourcc, serializer);
    sse_encode_u_64(self.modifier, serializer);
  }

  @protected
  void sse_encode_composition_reference(
      CompositionReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.internalproject, serializer);
    sse_encode_Uuid(self.internalid, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_folder_reference(
      FolderReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.internalproject, serializer);
    sse_encode_Uuid(self.internalid, serializer);
  }

  @protected
  void sse_encode_footage_reference(
      FootageReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.internalproject, serializer);
    sse_encode_Uuid(self.internalid, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_item_reference(ItemReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ItemReference_Footage(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_footage_reference(field0, serializer);
      case ItemReference_Solid(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_solid_reference(field0, serializer);
      case ItemReference_Composition(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_composition_reference(field0, serializer);
      case ItemReference_Folder(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_folder_reference(field0, serializer);
    }
  }

  @protected
  void sse_encode_layer_reference(
      LayerReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.internalprojectId, serializer);
    sse_encode_Uuid(self.internalcompId, serializer);
    sse_encode_Uuid(self.internallayerId, serializer);
  }

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          List<BridgeEffectInstance> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEffectInstance(
          item, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_item_reference(
      List<ItemReference> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_item_reference(item, serializer);
    }
  }

  @protected
  void sse_encode_list_layer_reference(
      List<LayerReference> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_layer_reference(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_lumit_media_status(
      LumitMediaStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_StreamSink_scoped_change_Sse(
      RustStreamSink<ScopedChange>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_StreamSink_scoped_change_Sse(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_item_reference(
      ItemReference? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_item_reference(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_layer_reference(
      LayerReference? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_layer_reference(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_project_reference(
      ProjectReference? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_project_reference(self, serializer);
    }
  }

  @protected
  void sse_encode_project_reference(
      ProjectReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.internalid, serializer);
  }

  @protected
  void sse_encode_scoped_change(ScopedChange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_project_reference(self.project, serializer);
    sse_encode_opt_box_autoadd_item_reference(self.item, serializer);
    sse_encode_opt_box_autoadd_layer_reference(self.layer, serializer);
  }

  @protected
  void sse_encode_solid_reference(
      SolidReference self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.internalproject, serializer);
    sse_encode_Uuid(self.internalid, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_worker_response(
      WorkerResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case WorkerResponse_RenderedDMABuf(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_bridge_shared_frame_info_linux(
            field0, serializer);
    }
  }
}

@sealed
class BridgeEffectInstanceImpl extends RustOpaque
    implements BridgeEffectInstance {
  // Not to be used by end users
  BridgeEffectInstanceImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BridgeEffectInstanceImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: BridgeLib
        .instance.api.rust_arc_increment_strong_count_BridgeEffectInstance,
    rustArcDecrementStrongCount: BridgeLib
        .instance.api.rust_arc_decrement_strong_count_BridgeEffectInstance,
    rustArcDecrementStrongCountPtr: BridgeLib
        .instance.api.rust_arc_decrement_strong_count_BridgeEffectInstancePtr,
  );

  List<String> getParameters() =>
      BridgeLib.instance.api.crateApiEffectBridgeEffectInstanceGetParameters(
        that: this,
      );

  /// A parameter's static scalar value.
  ///
  /// Only `Float` is carried so far, and only its static value: the other
  /// seven `EffectValue` shapes (point, colour, bool, choice, seed, file,
  /// layer) and the keyframed case have no Dart-side representation yet, so
  /// they answer `None` rather than silently reading as 0.0 — a colour
  /// parameter rendering as "0" is worse than one rendering as blank.
  ///
  /// TODO: replace this with a sum type mirroring `EffectValue`, so every
  /// parameter kind is expressible. Tracked in docs/TODO.md under "Bridge".
  double? getValue({required String id}) => BridgeLib.instance.api
      .crateApiEffectBridgeEffectInstanceGetValue(that: this, id: id);

  String name() =>
      BridgeLib.instance.api.crateApiEffectBridgeEffectInstanceName(
        that: this,
      );

  String serialize() =>
      BridgeLib.instance.api.crateApiEffectBridgeEffectInstanceSerialize(
        that: this,
      );

  /// Overwrite a parameter with a static scalar. Same limitation as
  /// [`Self::get_value`]: it can only express `Float`, so calling it on a
  /// parameter of another kind would change its type. It therefore refuses
  /// rather than corrupting the effect.
  void setValue({required String id, required double value}) =>
      BridgeLib.instance.api.crateApiEffectBridgeEffectInstanceSetValue(
          that: this, id: id, value: value);
}

@sealed
class BridgeErrorImpl extends RustOpaque implements BridgeError {
  // Not to be used by end users
  BridgeErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BridgeErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        BridgeLib.instance.api.rust_arc_increment_strong_count_BridgeError,
    rustArcDecrementStrongCount:
        BridgeLib.instance.api.rust_arc_decrement_strong_count_BridgeError,
    rustArcDecrementStrongCountPtr:
        BridgeLib.instance.api.rust_arc_decrement_strong_count_BridgeErrorPtr,
  );
}

@sealed
class EffectInstanceImpl extends RustOpaque implements EffectInstance {
  // Not to be used by end users
  EffectInstanceImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  EffectInstanceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        BridgeLib.instance.api.rust_arc_increment_strong_count_EffectInstance,
    rustArcDecrementStrongCount:
        BridgeLib.instance.api.rust_arc_decrement_strong_count_EffectInstance,
    rustArcDecrementStrongCountPtr: BridgeLib
        .instance.api.rust_arc_decrement_strong_count_EffectInstancePtr,
  );
}

@sealed
class LumitBridgeStateImpl extends RustOpaque implements LumitBridgeState {
  // Not to be used by end users
  LumitBridgeStateImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LumitBridgeStateImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        BridgeLib.instance.api.rust_arc_increment_strong_count_LumitBridgeState,
    rustArcDecrementStrongCount:
        BridgeLib.instance.api.rust_arc_decrement_strong_count_LumitBridgeState,
    rustArcDecrementStrongCountPtr: BridgeLib
        .instance.api.rust_arc_decrement_strong_count_LumitBridgeStatePtr,
  );
}
